---
- name: Register temporary directory
  tempfile: 
    state: directory
  register: tmp_directory

- name: check constellation
  stat:
    path: "{{ bin_install_dir }}/constellation-node"
  register: constellation_stat_result

- name: Download the constellation-node binary
  get_url: 
    url: "{{constellation.repo}}"
    dest: "{{tmp_directory.path}}"
  when: constellation_stat_result.stat.exists == False

- name: unzip the tar file
  shell: |
    cd "{{ tmp_directory.path }}"
    tar -xf constellation-"{{version}}"-ubuntu1604.tar.xz
  when: constellation_stat_result.stat.exists == False

- name: Create the bin directory
  file:
    path: "{{ bin_install_dir }}"
    state: directory
    recurse: yes
  when: constellation_stat_result.stat.exists == False

- name: This task puts the constellation-node binary into the bin directory
  copy:
    src: "{{ tmp_directory.path }}/constellation-{{version}}-ubuntu1604/constellation-node"
    dest: "{{ bin_install_dir }}/constellation-node"
    mode: 0755
    remote_src: yes
  when: constellation_stat_result.stat.exists == False
  