apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: warehousewarehouseibft
  namespace: warehouse-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: warehousewarehouseibft
  chart:
    git: https://github.com/Roshan13046/blockchain-automation-framework.git
    ref: feature/510
    path: platforms/hyperledger-besu/charts/node_besu
  values:
    metadata:
      namespace: warehouse-bes
      labels:
    replicaCount: 1
    staticnodes:
      - "enode://cf96ccd2b57c7360f7844531e7cc6611488a2f7a2b7eff0e79d9d4055f557c8d7d409e44d2fe200db797578691bc7f40a8c1eee592f62a77c6527e842be43359@validator1.supplychain-bes.svc.cluster.local:30303"
      - "enode://adf6fe295ee7871126d9fbacd242d923c9d33650a7e90a00f5d293b0a942311ebe4c5f3bc802dcc982b1c0dad9f71c7ed8a93f74c7d7d22e22d87cc6280f3460@validator2.supplychain-bes.svc.cluster.local:30303"
      - "enode://36e0d7d67a427503019f22ea233c09df3644d15e22aba97d3822a248b6e729c472c80705951c27fefe971aab95aa9a035b4c11e5f8e9ae24c12f2fc90a3fd721@validator3.supplychain-bes.svc.cluster.local:30303"
      - "enode://ae4d702c040844f4c0b6c5e5ceac10fbb6488ea154f6dd409d8302e6c5dacffba124e0d47f96572f5ebef1307136c30558b7d7c0b06c7aa13600b28cf6b7fa3b@validator4.supplychain-bes.svc.cluster.local:30303"
      - "enode://332e4947af2d50e396758b05b265588ca1ff055a141ec8b462fa1de3da768c496d492bb91ef2ff5403d203bb3881814d026c4aff9442a8de1802caa3adcc9a33@carrier.carrier-bes.svc.cluster.local:30303"
      - "enode://291d5b60f5f7cf58e00b28a9061c0f83b9e7f2e1ab4221ae7036fc61ce8e574c7da133078751bc97a752083fe081c1c0afd9272fad66c87d4afc9c57a86e3db5@manufacturer.manufacturer-bes.svc.cluster.local:30303"
      - "enode://2e01d2a33c4d17869ca0a3e530d44fd7797b7e5d9462f1ed3e242ac13f4963e51c994ae0300a986cc1611756e4d1b6b5c29c69b9cb8e3b2c3ea6f07e04df0232@store.store-bes.svc.cluster.local:30303"
      - "enode://002d5ade08ac1e6574c6e5b2e977a6193753fc7f79cea6326f1f469065e8f636b84653f0621fc2be1310d828b50c17df5482d96b8d10b62b8f9be59a082a38d2@warehouse.warehouse-bes.svc.cluster.local:30303"
   

    liveliness_check:
      enabled: false
    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5
      
    proxy:
      provider: none
      external_url: warehouse.warehouse-bes
      p2p: 30303
      rpc: 8545

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0     

    node:
      name: warehouse
      consensus: clique
      subject: O=Warehouse,OU=Warehouse,L=42.36/-71.06/Boston,C=US
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    tm:
      type: tessera
      tls: True
      
      url: "https://warehouse-tessera.warehouse-bes:8888"
      
    storage:
      storageclassname: gcpstorageclass
      storagesize: 1Gi

    vault:
      address: http://10.128.0.26:8200
      secretprefix: secret/warehouse-bes/crypto/warehouse
      serviceaccountname: vault-auth
      keyname: data
      tmdir: tm
      tlsdir: tls
      role: vault-role
      authpath: besuwarehouse

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImNsaXF1ZSI6IHsKICAgICAgImJsb2NrcGVyaW9kc2Vjb25kcyI6IDE1LAogICAgICAiZXBvY2hsZW5ndGgiOiAzMDAwMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDljNDkyN2I0ZTdlYjNiODAxYTFhN2EwMzkxOGQ1MTE3NDE5YWZlOWE5NDkzZTQzMjczYTU1ZGE0YjU3YjA3NGJkNzk5NzVhOWU2NTllNmUwYzU5NDExY2M1MTEyMzY5ZjAzNjUxMDk3MjRmNDk1ZDZlNzU0MDE0MzRkZTM5NDhjMTE0OWVlNjRkODQ3NGQxZDI0NjA1OTIwNGRkMzcxOWU4Nzg0MzQ4MDg0MDAwMDAwMDBjMCIKfQ==
