apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carriercarrieribft
  namespace: carrier-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carriercarrieribft
  chart:
    git: https://github.com/Roshan13046/blockchain-automation-framework.git
    ref: develop
    path: platforms/hyperledger-besu/charts/node_besu
  values:
    metadata:
      namespace: carrier-bes
      labels:
    replicaCount: 1
    staticnodes:
      - "enode://dc8b919cfdc6ab195a76003abe3e6635447822e70d991f13f3eef998c51538f5adc6fce78640f88df566a6046009bab1d6a1de5c4d38f25652bdce66f9bb9e28@validator1.test.besu.blockchaincloudpoc.com:30303"
      - "enode://5798669feb29fe50e78505e2a38f426c147c422669c4580f2a32ef44d3a3f51a714027c71ea6ae6dcad6d281c063fa9a0bf3da83116bcff17990e80d0a971e73@validator2.test.besu.blockchaincloudpoc.com:30303"
      - "enode://4c13c61289672ba6da2c759661ef87f64973d89891d2f911db821329ae870191a266c59df840501f5a584e078fb46e3698ff55aa9eeaebe6b5efb6a930b737a5@validator3.test.besu.blockchaincloudpoc.com:30303"
      - "enode://3cde2bdeaad7df8a6562e0144d0468510cdb1b7ec6c897b0569cc3053f919bd01a86606eab1ad7b17a6530b66fb855af976d86d56c75583c58dd162046787d73@validator4.test.besu.blockchaincloudpoc.com:30303"
      - "enode://0c5e3ddf0994c1868c0141dd0f66c694e6effa6d524524cc0b37fa02b10f3b2ed96f3b0089b5edeeb2f896525ab90075e3e2cc1a925c4a2222040bd635bd56fd@carrier.test.besu.blockchaincloudpoc.com:30303"
      - "enode://09f13d7cbdc80a9489b6760d4dfbf1fc93ce727113ed0c2a8577ea0073e26fa3b5d32d8086fc351ef69a9b22dd7e70dc5a803d708830448ed44f63740f6dd153@manufacturer.test.besu.blockchaincloudpoc.com:30303"
      - "enode://4b0b78f07a0f80e1f814461d8dcdc2d233b6c93603f47b9f7dd9e0c39ad660a9bd54d479bc178b855007e6ce30f6bb155f7eb98bf47ce40b8aa0c313be5874f7@store.test.besu.blockchaincloudpoc.com:30303"
      - "enode://26ba031e732e0eda0f99e2e9735aaa48b911e2c8658e4dab37ce449b9c554c5000153be91ad32989b95d0eed17980c8c71e6449edee2e09f4cecfe407f5ab6fb@warehouse.test.besu.blockchaincloudpoc.com:30303"
   

    liveliness_check:
      enabled: false
    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5
      
    proxy:
      provider: none
      external_url: carrier.carrier-bes
      p2p: 30303
      rpc: 8545

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0     

    node:
      name: carrier
      consensus: clique
      subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    tm:
      type: tessera
      tls: True
      
      url: "https://carrier-tessera.carrier-bes:8888"
      
    storage:
      storageclassname: gcpstorageclass
      storagesize: 1Gi

    vault:
      address: http://10.128.0.26:8200
      secretprefix: secret/carrier-bes/crypto/carrier
      serviceaccountname: vault-auth
      keyname: data
      tmdir: tm
      tlsdir: tls
      role: vault-role
      authpath: besucarrier

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImNsaXF1ZSI6IHsKICAgICAgImJsb2NrcGVyaW9kc2Vjb25kcyI6IDE1LAogICAgICAiZXBvY2hsZW5ndGgiOiAzMDAwMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDIxY2Q2MmE3ZmQ0ODc3YTk4NmIwNWU0MDgwM2ZiYjY5M2M4ZWQ3MmU5NDBlOTNjY2U1ZGE2NmI1Zjc1MDQyNmY3Y2FjMGVmZGJlNjE1OThhZWI5NDQwYjQ4ODE3ZmYzZWU0NGM5YmEzYWJhNjVhNGM3Njg0MzViMDEwNTk5NDg1YjVkMjkzZDA1ZjZkNmI4MzAwYzFjYzZkNDQ0OTBkMjUxZTE0ZWU4MDg0MDAwMDAwMDBjMCIKfQ==
