apiVersion: app/v1
kind: Deployment
metadata: 
  name: frontEnd
  namespace: frontend-ns
    labels: 
      apps: vitalam-fe
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: vitalam-fe
  template:
    metadata:
      annotations:
        checksum/service: {{ include (print $.Template.BasePath "/service.yaml") . | sha256sum }}
      labels:
        app: vitalam-fe
    spec:
      imagePullSecrets: 
        - name: regcred
      containers:
      - name: frontend
        env:
        - name: AUTH_DOMAIN
          value: {{ $.Values.config.applicationConfig.authDomain }}
        - name: CLIENT_ID
          value: {{ $.Values.config.applicationConfig.clientID }}
        - name: CUST_AUTH_CLIENT_ID
          value: {{ $.Values.config.applicationConfig.custAuthClientID }}
        - name: T1_AUTH_CLIENT_ID
          value: {{ $.Values.config.applicationConfig.t1AuthClientID }}
        - name: AUTH_AUDIENCE
          value: {{ $.Values.config.applicationConfig.authAudience }}
        - name: API_HOST
          value: {{ $.Values.config.applicationConfig.apiHost }}
        - name: API_PORT
          value: {{ $.Values.config.applicationConfig.apiPort }}
        - name: SUBSTRATE_HOST
          value: {{ $.Values.config.applicationConfig.substrateHost }}
        - name: SUBSTRATE_PORT
          value: {{ $.Values.config.applicationConfig.substratePort }}
        - name: VITALAM_DEMO_PERSONA
          value: {{ $.Values.config.applicationConfig.vitalamDemoPersona }}
        image: {{ $.Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        ports: 
        - containerPort: {{ $.Values.config.port }}
          name: http
          protocol: TCP

        {{- if .Values.config.enableLivenessProbe }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          failureThreshold: 5
          timeoutSeconds: 3
          periodSeconds: 10
        {{- end }}
