---
- name: Verify
  hosts: localhost
  tasks:

#####################################################################################
  #This task checks if the ca.key is created for orderers or not
  - name: Check if the ca.key is created for orderers or not
    stat:
      path: "./build/crypto-config/ordererOrganizations/testorderer/ca/testorderer-CA.key"
    register: ca_key_orderer_check
  
#####################################################################################
  #This task assert if the ca.key exists for orderers
  - name: Assert if the ca.key exists for orderers
    assert:
      that: ca_key_orderer_check.stat.exists

#####################################################################################
  #This task checks if the ca.pem is created for orderers or not
  - name: Check if the ca.pem is created for orderers or not
    stat:
      path: "./build/crypto-config/ordererOrganizations/testorderer/ca/ca.testorderer-cert.pem"
    register: ca_pem_orderer_check
  
#####################################################################################
  #This task assert if the ca.pem exists for orderers
  - name: Assert if the ca.pem exists for orderers
    assert:
      that: ca_pem_orderer_check.stat.exists

#####################################################################################
  #This task checks if the ca.key is created for peers or not
  - name: Check if the ca.key is created for peers or not
    stat:
      path: "./build/crypto-config/peerOrganizations/testpeer/ca/testpeer-CA.key"
    register: ca_key_peer_check
  
#####################################################################################
  #This task assert if the ca.key exists for peers
  - name: Assert if the ca.key exists for peers
    assert:
      that: ca_key_peer_check.stat.exists

#####################################################################################
  #This task checks if the ca.pem is created for peers or not
  - name: Check if the ca.pem is created for peers or not
    stat:
      path: "./build/crypto-config/peerOrganizations/testpeer/ca/ca.testpeer-cert.pem"
    register: ca_pem_peer_check
  
#####################################################################################
  #This task assert if the ca.pem exists for peers
  - name: Assert if the ca.pem exists for peers
    assert:
      that: ca_pem_peer_check.stat.exists

#####################################################################################
  #This task checks if the value file is created for CA of the orderers
  - name: Check if the value file is created for CA of the orderers
    stat:
      path: "test/test_ca/testorderer.yaml"
    register: orderer_ca_check
  
#####################################################################################
  #This task assert if the value file is created for CA of the orderers
  - name: Assert if the value file is created for CA of the orderers
    assert:
      that: orderer_ca_check.stat.exists

#####################################################################################
  #This task checks if the value file is created for CA of the peers
  - name: Check if the value file is created for CA of the peers
    stat:
      path: "test/test_ca/testpeer.yaml"
    register: peer_ca_check
  
#####################################################################################
  #This task assert if the value file is created for CA of the peers
  - name: Assert if the value file is created for CA of the peers
    assert:
      that: peer_ca_check.stat.exists

#####################################################################################
#####################################################################################
  #This task checks if the crypto_script is created for the orderers
  - name: Check if the crypto_script is created for orderers
    stat:
      path: "./build/generate-crypto-test_component_name-test_orderer.sh"
    register: gc_orderer_check
  
#####################################################################################
  #This task assert if the value file exists or not for orderers
  - name: Assert if the value file exists or not for orderers
    assert:
      that: gc_orderer_check.stat.exists

#####################################################################################
  #This task checks if the crypto_script is created for the peers
  - name: Check if the crypto_script is created for peers
    stat:
      path: "./build/generate-crypto-test_component_name.sh"
    register: gc_peer_check

#####################################################################################
  #This task assert if the value file exists or not for peers
  - name: Assert if the value file exists or not for peers
    assert:
      that: gc_peer_check.stat.exists

#####################################################################################
#####################################################################################
  #This task checks if the orderer1.key is created for orderers or not
  - name: Check if the orderer1.key is created for orderers or not
    stat:
      path: "./build/crypto-config/ordererOrganizations/testorderer/testorderer1-testorderer.key"
    register: orderer1_key_check
  
#####################################################################################
  #This task assert if the orderer1.key exists for orderers
  - name: Assert if the orderer1.key exists for orderers
    assert:
      that: orderer1_key_check.stat.exists

#####################################################################################
  #This task checks if the orderer2.key is created for orderers or not
  - name: Check if the orderer2.key is created for orderers or not
    stat:
      path: "./build/crypto-config/ordererOrganizations/testorderer/testorderer2-testorderer.key"
    register: orderer2_key_check
  
#####################################################################################
  #This task assert if the orderer2.key exists for orderers
  - name: Assert if the orderer2.key exists for orderers
    assert:
      that: orderer2_key_check.stat.exists

#####################################################################################
  #This task checks if the orderer1.csr is created for orderers or not
  - name: Check if the orderer1.csr is created for orderers or not
    stat:
      path: "./build/crypto-config/ordererOrganizations/testorderer/testorderer1-testorderer.csr"
    register: orderer1_csr_check
  
#####################################################################################
  #This task assert if the orderer1.csr exists for orderers
  - name: Assert if the orderer1.csr exists for orderers
    assert:
      that: orderer1_csr_check.stat.exists

#####################################################################################
  #This task checks if the orderer2.csr is created for orderers or not
  - name: Check if the orderer2.csr is created for orderers or not
    stat:
      path: "./build/crypto-config/ordererOrganizations/testorderer/testorderer2-testorderer.csr"
    register: orderer2_csr_check
  
#####################################################################################
  #This task assert if the orderer2.csr exists for orderers
  - name: Assert if the orderer2.csr exists for orderers
    assert:
      that: orderer2_csr_check.stat.exists

#####################################################################################
  #This task checks if the orderer1.pem is created for orderers or not
  - name: Check if the orderer1.pem is created for orderers or not
    stat:
      path: "./build/crypto-config/ordererOrganizations/testorderer/testorderer1-testorderer.pem"
    register: orderer1_pem_check
  
#####################################################################################
  #This task assert if the orderer1.pem exists for orderers
  - name: Assert if the orderer1.pem exists for orderers
    assert:
      that: orderer1_pem_check.stat.exists

#####################################################################################
  #This task checks if the orderer2.pem is created for orderers or not
  - name: Check if the orderer2.pem is created for orderers or not
    stat:
      path: "./build/crypto-config/ordererOrganizations/testorderer/testorderer2-testorderer.pem"
    register: orderer2_pem_check
  
#####################################################################################
  #This task assert if the orderer2.pem exists for orderers
  - name: Assert if the orderer2.pem exists for orderers
    assert:
      that: orderer2_pem_check.stat.exists

#####################################################################################
  #This task checks if the orderer1.certchain is created for orderers or not
  - name: Check if the orderer1.certchain is created for orderers or not
    stat:
      path: "./build/crypto-config/ordererOrganizations/testorderer/testorderer1-testorderer-certchain.pem"
    register: orderer1_certchain_check
  
#####################################################################################
  #This task assert if the orderer1.certchain exists for orderers
  - name: Assert if the orderer1.certchain exists for orderers
    assert:
      that: orderer1_certchain_check.stat.exists

#####################################################################################
  #This task checks if the orderer2.certchain is created for orderers or not
  - name: Check if the orderer2.certchain is created for orderers or not
    stat:
      path: "./build/crypto-config/ordererOrganizations/testorderer/testorderer2-testorderer-certchain.pem"
    register: orderer2_certchain_check
  
#####################################################################################
  #This task assert if the orderer2.certchain exists for orderers
  - name: Assert if the orderer2.certchain exists for orderers
    assert:
      that: orderer2_certchain_check.stat.exists