#Provide the nodeName for node
#Eg. nodeName: bank1
nodeName: notarykd

#Provide the replica set for node deployed
#Eg. replicas: 1
replicas: 1

metadata:
  #Provide the namespace
  #Eg. namespace: default
  namespace: supplychainkd-ns
  #Provide the custom labels
  #NOTE: Provide labels other than name, release name , release service, chart version , chart name , app.
  #Eg. labels:
  #      role: create_channel
dockerImagePki:
  name: corda/enterprise-pkitool
  tag: 1.2-zulu-openjdk8u242
  pullPolicy: Always
  
image:
  initContainerName: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
  imagePullSecret: regcred
     
volume:
  baseDir: /opt/corda

vault:
  address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:8200
  role: vault-role
  authpath: cordanotarykd
  serviceaccountname: vault-auth
  dbsecretprefix: notarykd/credentials/database
  rpcusersecretprefix: notarykd/credentials/rpcusers
  tokensecretprefix: notarykd/credentials/vaultroottoken
  keystoresecretprefix: notarykd/credentials/keystore
  certsecretprefix: notarykd/certs
    
healthcheck:
  #Provide the interval in seconds you want to iterate till db to be ready
  #Eg. readinesscheckinterval: 5
  readinesscheckinterval: 10
  #Provide the threshold till you want to check if specified db up and running
  #Eg. readinessthreshold: 2
  readinessthreshold: 15

serviceSsh:
  type: ClusterIP
  port: 2222
  targetPort: 2222
  nodePort:
  
shell:
  user: signer
  password: signerP

# required parameter
idmanPublicIP: 52.210.203.127

idmanPort: 10000

serviceLocations:
  identityManager:
    host: idman-internal
    port: 5052
  networkMap:
    host: nmap-internal
    port: 5050
  revocation:
    port: 5053

signers:
  CSR:
    schedule:
      interval: 1m
  CRL:
    schedule:
      interval: 1d
  NetworkMap:
    schedule:
      interval: 1m
  NetworkParameters:
    schedule:
      interval: 1m

cordaJarMx: 1

healthCheckNodePort: 0

# where is CENM service jar file stored
jarPath: bin

# where is CENM service configuration file stored
configPath: etc

pki:
  certificates:
    tlscrlsigner:
      subject: "CN=Test TLS Signer Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
      crl:
        issuer: "CN=Corda TLS Signer Certificate, OU=Corda, O=R3 HoldCo LLC, L=New York, C=US"
    cordarootca:
      subject: "CN=Test Root CA Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
    subordinateca:
      subject: "CN=Test Subordinate CA Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
    identitymanagerca:
      subject: "CN=Test Identity Manager Service Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
    networkmap:
      subject: "CN=Test Network Map Service Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
