##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins-{{ .Values.service.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: plugins-{{ .Values.service.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "labels.custom" . | nindent 2 }}
data:
  PLUGINS: |
    {  
    "packageName" : {{ .Values.plugins.packageName | quote }},
    "type" : {{ .Values.plugins.type | quote }},
    "action" : {{ .Values.plugins.action | quote }},
    "options": {
      "rpcApiHttpHost" : {{ .Values.plugins.rpcApiHttpHost | quote }},
      "rpcApiWsHost" : {{ .Values.plugins.rpcApiWsHost | quote }},
      "instanceId" : {{ .Values.plugins.instanceId | quote }} 
      }
    }