#############################################################################################
# This role creates value files for storage class
#############################################################################################

# Check StorageClass exists already
- name: Check if storageclass exists
  k8s_facts:
    kind: StorageClass
    name: "{{ storageclass_name }}"
    kubeconfig: "{{ kubernetes.config_file }}"
  register: storageclass_state

# Create StorageClass
- name: Create storageclass
  include_role:
    name: create/k8_component
  vars:
    component_type: "{{ provider }}-storageclass"
    component_type_name: "{{ organization.name | lower }}"
    component_name: "{{ component_type_name }}-{{ storageclass_name }}"
    release_dir: "{{ playbook_dir }}/../../../{{ organization.gitops.release_dir }}"
  when: storageclass_state.resources|length == 0


# Push the deployment files to repository
- name: "Push the created deployment files to repository"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    GIT_REPO: "{{ organization.gitops.git_push_url }}"
    GIT_USERNAME: "{{ organization.gitops.username }}"
    GIT_PASSWORD: "{{ organization.gitops.password }}"
    GIT_BRANCH: "{{ organization.gitops.branch }}"
    GIT_RESET_PATH: "platforms/hyperledger-indy/configuration"
    msg: "Pushing deployment file for storageclass"

- name: "Wait for Storageclass creation for {{ component_name }}"
  include_role:
    name: check/k8_component
  vars:
    component_type: "StorageClass"
    component_name: "{{ storageclass_name }}"
    kubeconfig: "{{ kubernetes.config_file }}"
  when: storageclass_state.resources|length == 0