#############################################################################################
# This role creates value files for service account for vault
#############################################################################################

# Create vault auth service account per identity of trustees
- name: Create vault auth service account for {{ identity }}
  include_role:
    name: create/k8_component
  vars:
    component_namespace: "{{ component_ns }}"
    identity: "{{ trusteeItem.name }}"
    component_type: "{{ identity }}-vault-auth"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}"
  loop: "{{ services.trustees }}"
  loop_control:
    loop_var: trusteeItem
  when: services.trustees is defined

# Create vault auth service account per identity of stewards
- name: Create vault auth service account for {{ identity }}
  include_role:
    name: create/k8_component
  vars:
    component_namespace: "{{ component_ns }}"
    identity: "{{ stewardItem.name }}"
    component_type: "{{ identity }}-vault-auth"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}"
  loop: "{{ services.stewards }}"
  loop_control:
    loop_var: stewardItem
  when: services.stewards is defined

# Create vault auth service account per identity of endorsers
- name: Create vault auth service account for {{ identity }}
  include_role:
    name: create/k8_component
  vars:
    component_namespace: "{{ component_ns }}"
    identity: "{{ endorserItem.name }}"
    component_type: "{{ identity }}-vault-auth"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}"
  loop: "{{ services.endorsers }}"
  loop_control:
    loop_var: endorserItem
  when: services.endorsers is defined

  # Create vault auth service account per organizations
  - name: Create vault auth service account for {{ organization }}
    include_role:
      name: create/k8_component
    vars:
      component_namespace: "{{ component_ns }}"
      component_type: "{{ organization }}-vault-auth"
      release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}"