---
  - name: Cleanup
    hosts: localhost
    tasks:

#####################################################################################
      #This task deletes the temporarily created build directory
      - name: Delete the test directory
        file:
          path: "./build"
          state: absent
