---
- name: Converge
  hosts: localhost
  connection: local
  tasks:

#####################################################################################
    # Testing create/crypto_script role for orderer
    - name: "Include configuration/roles/create/crypto_script"
      include_role:
        name: "configuration/roles/create/crypto_script"
      vars:
        component_type: orderer
        component_name: test_component_name
        item:
          name: test_name
          country: test_country
          subject: test_subject
          state: test_state
          location: test_location
          external_url_suffix: test_url
          ca_data:
            url: test_ca_data_url
        orderers:
          - orderer:
            name: test_orderer
            type: orderer
            consensus: kafka
            grpc:
              port: 7050

#####################################################################################
    # Testing create/crypto_script for peers
    - name: "Include configuration/roles/create/crypto_script"
      include_role:
        name: "configuration/roles/create/crypto_script"
      vars:
        component_type: peer
        component_name: test_component_name
        item:
          name: test_name
          country: test_country
          subject: test_subject
          state: test_state
          location: test_location
          external_url_suffix: test_url
          ca_data:
            url: test_ca_data_url
          services:
            peers:
            - peer:
            - peer:
