---
- name: Verify
  hosts: localhost
  tasks:

#####################################################################################
  #This task checks if the crypto_script is created for the orderers
  - name: Check if the crypto_script is created for orderers
    stat:
      path: "./build/generate-crypto-test_component_name-test_orderer.sh"
    register: gc_orderer_check
  
#####################################################################################
  #This task assert if the value file exists or not for orderers
  - name: Assert if the value file exists or not for orderers
    assert:
      that: gc_orderer_check.stat.exists

#####################################################################################
  #This task checks if the crypto_script is created for the peers
  - name: Check if the crypto_script is created for peers
    stat:
      path: "./build/generate-crypto-test_component_name.sh"
    register: gc_peer_check

#####################################################################################
  #This task assert if the value file exists or not for peers
  - name: Assert if the value file exists or not for peers
    assert:
      that: gc_peer_check.stat.exists
