---
# We have enabled additional ports on Ambassador for TCP. By default 8443 is exposed.
# The extra ports are pass as parameter --set ambassador.otherPorts={10010,10020} is taken from network.env.ambassadorPorts
- name: Install Ambassador
  shell: |
    KUBECONFIG={{ kubeconfig_path }} helm upgrade --install --set ambassador.otherPorts={"{{ network.env.ambassadorPorts }}"} --set ambassador.targetPort={{ ambassador.targetPort }} --set ambassador.port={{ ambassador.port }} --set ambassador.tag={{ ambassador.tag }} --set ambassador.image={{ ambassador.image }} ambassador {{ playbook_dir }}/../../../platforms/shared/charts/ambassador
  tags:
    - ambassador

# Wait for Ambassador pods to start running
- name: wait for pods to come up
  k8s_facts:
    kind: Pod
    namespace: default
    kubeconfig: "{{ kubeconfig_path }}"
    context: "{{ kubecontext }}"
    label_selectors:
      - app.kubernetes.io/name = ambassador
    field_selectors:
      - status.phase=Running    
  register: kubectl_get_pods
  until: kubectl_get_pods.resources|length > 0
  retries: 5
  delay: 15

