---
sudo: required
language: python

stages:
  - test
  - name: build
    if: branch IN (master, develop) OR tag =~ /^(v)/
  
jobs:
  fast_finish: true
  include:
  - env: SCENARIO=default
  - env: SCENARIO=kubernetes-corda
  - env: SCENARIO=kubernetes-fabric
  - env: SCENARIO=kubernetes-indy
services:
- docker
  
install:
- pip install molecule yamllint ansible-lint docker openshift
  
script:
- cd platforms/shared/configuration
- molecule test -s $SCENARIO