---
dist: xenial
os: linux
language: python

jobs:
  fast_finish: true
  include:
    - stage: test
      env: 
        - SCENARIO=default
    - env: SCENARIO=kubernetes-corda
    - env: SCENARIO=kubernetes-fabric
    - env: SCENARIO=kubernetes-indy
    - stage: build
      if: (branch IN ("master", "develop") AND type = push) OR tag =~ /^(v)/
      script:
        - echo "here"
        - echo "there"

services:
- docker

before_install:
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
  - sudo apt-get install -y nodejs

install:
- pip install molecule yamllint ansible-lint docker openshift
  
script:
- cd platforms/shared/configuration
- molecule test -s $SCENARIO