apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    flux.weave.works/antecedent: carrier-net:helmrelease/carrier-net-ca-tools
  creationTimestamp: "2020-08-21T17:09:49Z"
  generation: 2
  labels:
    name: ca-tools
  name: ca-tools
  namespace: carrier-net
  resourceVersion: "2058"
  selfLink: /apis/extensions/v1beta1/namespaces/carrier-net/deployments/ca-tools
  uid: ea13333f-0375-43ee-85bc-3a8cdafd60ba
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: ca-tools
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: ca-tools
    spec:
      containers:
      - command:
        - sh
        - -c
        - /bin/bash
        image: hyperledger/fabric-ca-tools:1.2.0
        imagePullPolicy: IfNotPresent
        name: ca-tools
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /root/ca-tools
          name: ca-tools-pv
        - mountPath: /crypto-config
          name: ca-tools-crypto-pv
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ca-tools-pv
        persistentVolumeClaim:
          claimName: ca-tools-pvc
      - name: ca-tools-crypto-pv
        persistentVolumeClaim:
          claimName: ca-tools-crypto-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-08-21T17:12:10Z"
    lastUpdateTime: "2020-08-21T17:12:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-08-21T17:09:49Z"
    lastUpdateTime: "2020-08-21T17:12:10Z"
    message: ReplicaSet "ca-tools-599c8b474d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
