##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################


#This task creates the value files for each validator node of organization
- name: Create value file for member of each node
  include_tasks: nested_main.yaml
  loop: "{{ peers }}"
  loop_control:
    loop_var: peer
  when: peer.type == 'member'
