apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: manufacturer-net-ca
  namespace: manufacturer-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: manufacturer-net-ca
  chart:
    git: ssh://git@innersource.accenture.com/sow11/blockchain-automation-framework.git
    ref: feature/bafdemo
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: manufacturer-net
    server:
      name: ca
      tlsstatus: true
      admin: manufacturer-admin
    storage:
      storageclassname: manufacturersc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://a2f30bbf3fa6b11e9b7a50a059b1d738-111223046.eu-west-2.elb.amazonaws.com:9000
      authpath: manufacturer-net-auth
      secretcert: secret/crypto/peerOrganizations/manufacturer-net/ca?ca.manufacturer-net-cert.pem
      secretkey: secret/crypto/peerOrganizations/manufacturer-net/ca?manufacturer-net-CA.key
      secretadminpass: secret/credentials/manufacturer-net/ca/manufacturer?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    ambassador:
    #Provide annotations for ambassador service configuration
    #Only use HTTPS as HTTP and HTTPS don't work together ( https://github.com/datawire/ambassador/issues/1000 )
      annotations: |- 
        ---
        apiVersion: ambassador/v1
        kind:  Mapping
        name:  ca_manufacturer-net_mapping
        prefix: /
        host: ca.manufacturer-net:7054
        service: ca.manufacturer-net:7054
        tls: ca_manufacturer-net_tls
        ---
        apiVersion: ambassador/v1
        kind: TLSContext
        name: ca_manufacturer-net_tls
        hosts:
        - ca.manufacturer-net
        secret: ca-manufacturer-net-ambassador-certs
    