apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.node.name }}-config
  namespace: {{ $.Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Values.node.name }}-config
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  indy_config.py: |-  
{{ .Files.Get "indy_config.py" | indent 4}}