apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Values.metadata.name }}"
  namespace: "{{ $.Values.metadata.namespace }}"
  {{ if $.Values.ambassador.annotations }}
  annotations:
    getambassador.io/config: | 
    {{ $.Values.ambassador.annotations  | nindent 6 }}
  {{ end }}
spec:
  ports:
  - name: indy-node-node
    port: {{ $.Values.service.ports.nodePort }}
    targetPort: {{ $.Values.service.ports.nodeTargetPort }}
  - name: indy-node-client
    port: {{ $.Values.service.ports.clientPort }}
    targetPort: {{ $.Values.service.ports.clientTargetPort }}
  selector:
    app: "{{ $.Values.metadata.name }}"