apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: storestoreibft
  namespace: store-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: storestoreibft
  chart:
    git: https://github.com/Roshan13046/blockchain-automation-framework.git
    ref: feature/510
    path: platforms/hyperledger-besu/charts/node_besu
  values:
    metadata:
      namespace: store-bes
      labels:
    replicaCount: 1
    staticnodes:
      - "enode://28f8c9a676bc0d655f54236f510e64346c4e2e39b1d291fe3e4b2de513482a15d3e818cb747d206907b6c247eea7f00a94ed9297bb5270ba99808ac5f57ac125@validator1.supplychain-bes.svc.cluster.local:30303"
      - "enode://8cfbfb075a0781ddae0ffebb42873f13101950b6e424308c51ab20d45ea04053e9dc6b4f1b9625c43bf24d78a1bb41e5608e060453aa67cee2c121f142e768a7@validator2.supplychain-bes.svc.cluster.local:30303"
      - "enode://ccb2c99308195c31b13577d217f15fea1b9118390af52c4712c3bfe61e0a0b2caad98f50b3a375c34c76808bfa3c235c21455c563eae7c6248c3cfa906cb2254@validator3.supplychain-bes.svc.cluster.local:30303"
      - "enode://19c2d09e7248ca6c12a71de06fa622431dbe91da6ed098492548d2c40cf72b84bbf40d59bb58ae2ac6d0c8942f66618dcaf1c6392dfd9767f2854958963882f4@validator4.supplychain-bes.svc.cluster.local:30303"
      - "enode://7b033536d72348c86c5268487e2e7de3a6f4e7723b5a02db7dda9797bf4954efbddf8b62943677eca59e9c7dba74bdf1f302b034e5dba93ed8e8a09731aa4563@carrier.carrier-bes.svc.cluster.local:30303"
      - "enode://b06c3b0ff509ce4b3714b5b9a6a608fa4dc6dfb7328246c690ae5c5233f980b08cb978c9d481dab84da9f909c513c60be56568288e142843d84e5ca63a994016@manufacturer.manufacturer-bes.svc.cluster.local:30303"
      - "enode://d11060b703a74fb22003275a0036c2ffaf2b1fc4c6923e96d8c4389314c1831b2769ff7156fd0d000577ee4a5349e794f5420ba7d3c034e8af5278a46252d116@store.store-bes.svc.cluster.local:30303"
      - "enode://d5845ae06a714e7a1f0cd680ab01864dd54796ab525f6054016a5c4012670c3f42b7c1d809b0f71d14aaca9f77238ca880eb076424c05dbde9d6eb91a2cbb944@warehouse.warehouse-bes.svc.cluster.local:30303"
   

    liveliness_check:
      enabled: false
    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5
      
    proxy:
      provider: none
      external_url: store.store-bes
      p2p: 30303
      rpc: 8545

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0     

    node:
      name: store
      consensus: clique
      subject: O=Store,OU=Store,L=40.73/-74/New York,C=US
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    tm:
      type: tessera
      tls: True
      
      url: "https://store-tessera.store-bes:8888"
      
    storage:
      storageclassname: gcpstorageclass
      storagesize: 1Gi

    vault:
      address: http://10.128.0.26:8200
      secretprefix: secret/store-bes/crypto/store
      serviceaccountname: vault-auth
      keyname: data
      tmdir: tm
      tlsdir: tls
      role: vault-role
      authpath: besustore

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImNsaXF1ZSI6IHsKICAgICAgImJsb2NrcGVyaW9kc2Vjb25kcyI6IDE1LAogICAgICAiZXBvY2hsZW5ndGgiOiAzMDAwMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDY3ZTk1YzRmMDgxY2RiY2UzZGYwYTI4Zjk5NzUyNWNlNTIzOTQ2YTE5NDY0NThkOWFlMjMwNmRhZTIyNDRjODZlYjExYzYxMDZlOWE2ZThmNzU5NDJhNzQ4OWE1MjY2NGYxMTQ4ZWU0YWNhYWVkNTk5OTY0YWNiM2FiMzc5NDIzN2MyOTA3YzM1NjhkNGI5MWIzOTZiZmQ4ZTY5NTIyMjlkMTI5OGQ4MDg0MDAwMDAwMDBjMCIKfQ==
