apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: join-allchannel-warehouse-peer0
  namespace: warehouse-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: join-allchannel-warehouse-peer0
  chart:
    git: ssh://git@innersource.accenture.com/sow11/blockchain-automation-framework.git
    ref: feature/bafdemo
    path: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: warehouse-net

    peer:
      name: peer0
      address: peer0.warehouse-net.org4.demo.aws.blockchaincloudpoc.com:15010
      localmspid: warehouseMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://a7138542f18e311ea802e062682cead8-2102258106.eu-west-1.elb.amazonaws.com:9000
      authpath: warehouse-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/warehouse-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/warehouse-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer.org1.demo.aws.blockchaincloudpoc.com:8443
    anchorstx: |-
      CskCChAKDggCIgphbGxjaGFubmVsErQCCrECCgphbGxjaGFubmVsElwSWgoLQXBwbGljYXRpb24S
      SwgBEj8KDHdhcmVob3VzZU1TUBIvGgcKA01TUBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAi
      CgoGQWRtaW5zEgAqBkFkbWlucxrEARLBAQoLQXBwbGljYXRpb24SsQEIARKkAQoMd2FyZWhvdXNl
      TVNQEpMBCAEaBwoDTVNQEgAaWAoLQW5jaG9yUGVlcnMSSRI/Cj0KOHBlZXIwLndhcmVob3VzZS1u
      ZXQub3JnNC5kZW1vLmF3cy5ibG9ja2NoYWluY2xvdWRwb2MuY29tEKJ1GgZBZG1pbnMiCwoHUmVh
      ZGVycxIAIgsKB1dyaXRlcnMSACIKCgZBZG1pbnMSACoGQWRtaW5zKgZBZG1pbnM=
 