---
deployment:
  annotations: 
nodeName:
metadata:
  namespace:
  labels:

dockerImagePki:
  name:
  tag:
  pullPolicy:

storage:
  name:

replicas:

image:
  initContainerName:
  imagePullSecret:

dockerImageSigner:
  name:
  tag:
  pullPolicy:

# required parameter
acceptLicense: YES


service:
  type:
  port:

volume:
  baseDir:

vault:
  address:
  role:
  authpath:
  serviceaccountname:
  tokensecretprefix:
  certsecretprefix:

healthcheck:
  #Provide the interval in seconds you want to iterate till certificates to be ready
  #Eg. readinesscheckinterval: 10
  readinesscheckinterval:
  readinessthreshold:

serviceSsh:
  type:
  port:
  targetPort:
  nodePort:

shell:
  user:
  password:

# required parameter
idmanPublicIP:

idmanPort:

serviceLocations:
  identityManager:
    host:
    port:
  networkMap:
    host:
    port:
  revocation:
    port:

signers:
  CSR:
    schedule:
      interval:
  CRL:
    schedule:
      interval:
  NetworkMap:
    schedule:
      interval:
  NetworkParameters:
    schedule:
      interval:

cordaJarMx:

healthCheckNodePort:

# where is CENM service jar file stored
jarPath:

# where is CENM service configuration file stored
configPath:
