# Default values for Identity Manager service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  annotations: {}

# Provide the name of the node
# Eg. nodeName: idman
nodeName: idman

# This section contains the Enterprise-Corda node metadata.
metadata:
  # Provide the namespace for the Corda node.
  # Eg. namespace: cenm
  namespace: supplychainkd-ns
  # Provide the labels to the Corda node.
  labels:

pvc:
  #   annotations:
  #     key: "value"
  annotations: {}

# This section contains the storage information.
storage:
  # Provide the name of the storageclass.
  # NOTE: Make sure that the storageclass exist prior to this deployment as
  # this chart doesn't create the storageclass.
  # Eg. name: cenm
  name: abcd

# Provide the number of replicas for your pods
# Eg. replicas: 1
replicas: 1

# Provide image for init container
image:
  # Provide the alpine utils image.
  # NOTE: The alpine image used is the base alpine image with CURL installed.
  # Eg. initContainerName: hyperledgerlabs/alpine-utils:1.0
  initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
  # Provide the docker-registry secret created and stored in kubernetes cluster as a secret.
  # Eg. imagePullSecret: regcred
  imagepullsecret: regcred

# Provide image for idman container
dockerImage:
  # EX. name: corda/enterprise-identitymanager
  name: corda/enterprise-identitymanager
  # Ex tag: 1.2-zulu-openjdk8u242
  tag: 1.2-zulu-openjdk8u242
  # Ex. pullPolicy: Always
  pullPolicy: Always
  # EX. imagePullSecret: cenm-registry
  imagePullSecret: cenm-registry

# required parameter
# Accept license should be YES.
acceptLicense: YES

# This section contains the vault related information.
# NOTE: Make sure that the vault is already unsealed, intialized and configured to
# use the Kubernetes service account token based authentication.
vault:
  # Provide the vault address
  # Eg. address: http://vault.example.com:8200
  address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:8200
  # Provide the vault role used.
  # Eg. role: vault-role
  role: vault-role
  # Provide the authpath configured to be used.
  # Eg. authpath: entcordacenm
  authpath: cordanotarykd
  # Provide the service account name autheticated to vault.
  # NOTE: Make sure that the service account is already created and autheticated to use the vault.
  # Eg. serviceaccountname: vault-auth
  serviceaccountname: vault-auth
  # Provide the vault path where the  certificates are stored
  # Eg. certsecretprefix: secret/cenm-ns
  certsecretprefix: notarykd/certs

# Provide volume related specifications
volume:
 # Ex baseDir: /opt/corda
  baseDir: /opt/corda

# idman service 
service:
  # Ex. port: 10000
  port: 10000

serviceInternal:
  # internal port inside cluster
  # Ex. port: 5052
  port: 5052

serviceRevocation:
  # Revocation port inside cluster
  # Ex port: 5053
  port: 5053

# ssh service related configuration
shell:
  # Ex. sshdPort: 2222
  sshdPort: 2222
  # ssh username
  # Ex. user: idman
  user: idman
  # ssh password
  # Ex. idmanP
  password: idmanP  

# Database configuration
database:
  # Ex. driverClassName: "org.h2.Driver"
  driverClassName: "org.h2.Driver"
  # Ex. url: "jdbc:h2:file:./h2/identity-manager-persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=0;AUTO_SERVER_PORT=0"
  url: "jdbc:h2:file:./h2/identity-manager-persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=0;AUTO_SERVER_PORT=0"
  # Ex. user: "example-db-user"
  user: "example-db-user"
  # Ex. password: "example-db-password"
  password: "example-db-password"
  # Ex. runMigration: "true"
  runMigration: "true"

# Specify the maximum size of the memory allocation pool
# cordaJarMx: 1
cordaJarMx: 1

# healthCheckNodePort set to get rid of logs pollution
# Ex. healthCheckNodePort: 0
healthCheckNodePort: 0

# where is CENM service jar file stored
jarPath: bin

# where is CENM service configuration file stored
configPath: etc

# Sleep time after any error encountered in starting idman
sleepTimeAfterError: 120

healthcheck:
  #Provide the interval in seconds you want to iterate till db to be ready
  #Eg. readinesscheckinterval: 5
  readinesscheckinterval: 10
  #Provide the threshold till you want to check if specified db up and running
  #Eg. readinessthreshold: 2
  readinessthreshold: 15