# Default values for Identity Manager service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  annotations: {}

bashDebug: false

nodeName: idman

metadata:
  namespace: 
  labels:

pvc:
  #   annotations:
  #     key: "value"
  annotations: {}

storage:
  name: awsstorageclass

replicas: 1

image:
  initContainerName: 
  imagepullsecret: regcred

dockerImage:
  name: corda/enterprise-identitymanager
  tag: 1.2-zulu-openjdk8u242
  pullPolicy: Always

# required parameter
acceptLicense: YES

# This section contains the vault related information.
# NOTE: Make sure that the vault is already unsealed, intialized and configured to
# use the Kubernetes service account token based authentication.
vault:
  # Provide the vault address
  # Eg. address: http://vault.example.com:8200
  address:
  # Provide the vault role used.
  # Eg. role: vault-role
  role:
  # Provide the authpath configured to be used.
  # Eg. authpath: entcordacenm
  authpath:
  # Provide the service account name autheticated to vault.
  # NOTE: Make sure that the service account is already created and autheticated to use the vault.
  # Eg. serviceaccountname: vault-auth
  serviceaccountname:
  tokensecretprefix:
  # Provide the vault path where the  certificates are stored
  # Eg. certsecretprefix: secret/cenm-ns/signer/certs
  certsecretprefix:

# Provide volume related specificateions
volume:
 # Ex baseDir: /opt/corda
  baseDir:

service:
  type: LoadBalancer
  port: 10000

serviceInternal:
  type: LoadBalancer
  port: 5052

serviceRevocation:
  port: 5053

serviceSsh:
  type: LoadBalancer

shell:
  sshdPort: 2222
  user: idman
  password: idmanP  

database:
  driverClassName: "org.h2.Driver"
  url: "jdbc:h2:file:./h2/identity-manager-persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=0;AUTO_SERVER_PORT=0"
  user: "example-db-user"
  password: "example-db-password"
  runMigration: "true"

# required parameter
idmanPublicIP:

cordaJarMx: 1

healthCheckNodePort: 0

# where is CENM service jar file stored
jarPath: bin

# where is CENM service configuration file stored
configPath: etc

sleepTimeAfterError: 120
sleepTime: 0

healthcheck:
  #Provide the interval in seconds you want to iterate after for checking certificates
  #Eg. readinesscheckinterval: 10
  readinesscheckinterval:
  # Provide this to iterate till this to check for the certificates
  # readinessthreshold: 20
  readinessthreshold: