apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: ch-peer0
  namespace: ch-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: ch-peer0
  chart:
    git: git@github.com:himanshulalarya/blockchain-automation-framework.git
    ref: molecule
    path: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: ch-net
      images:
        couchdb: hyperledger/fabric-couchdb:0.4.18
        peer: hyperledger/fabric-peer:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        
    peer:
      name: peer0
      gossippeeraddress: peer0.ch-net.hf.dev.aws.blockchaincloudpoc-develop.com:8443
      gossipexternalendpoint: peer0.ch-net.hf.dev.aws.blockchaincloudpoc-develop.com:8443
      localmspid: chMSP
      loglevel: info
      tlsstatus: true
      couchdb:
        username: ch-user

    storage:
      peer:
        storageclassname: chsc
        storagesize: 512Mi
      couchdb:
        storageclassname: chsc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:8200
      authpath: ch-net-auth
      secretprefix: secret/crypto/peerOrganizations/ch-net/peers/peer0.ch-net
      secretambassador: secret/crypto/peerOrganizations/ch-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secret/credentials/ch-net/couchdb/ch?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: haproxy
      external_url_suffix: hf.dev.aws.blockchaincloudpoc-develop.com
