apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-manufacturer
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: anchorpeer-allchannel-manufacturer
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: manufacturer-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.manufacturer-net:7051
      localmspid: manufacturerMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://192.168.49.1:8200
      authpath: localmanufacturer-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/manufacturer-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/manufacturer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.supplychain-net:7050
    anchorstx: |-
      CqwCChAKDggCIgphbGxjaGFubmVsEpcCCpQCCgphbGxjaGFubmVsEl8SXQoLQXBwbGljYXRpb24S
      TggBEkIKD21hbnVmYWN0dXJlck1TUBIvGgcKA01TUBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJz
      EgAiCgoGQWRtaW5zEgAqBkFkbWlucxqkARKhAQoLQXBwbGljYXRpb24SkQEIARKEAQoPbWFudWZh
      Y3R1cmVyTVNQEnEIARoHCgNNU1ASABo2CgtBbmNob3JQZWVycxInEh0KGwoWcGVlcjAubWFudWZh
      Y3R1cmVyLW5ldBCLNxoGQWRtaW5zIgsKB1dyaXRlcnMSACIKCgZBZG1pbnMSACILCgdSZWFkZXJz
      EgAqBkFkbWlucyoGQWRtaW5z

