apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: chaincode-install-manufacturer-peer0-1
  namespace: manufacturer-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: chaincode-install-manufacturer-peer0-1
  chart:
    git: ssh://git@innersource.accenture.com/sow11/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/install_chaincode
  values:
    metadata:
      namespace: manufacturer-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/sownak/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.manufacturer-net:7051
      localmspid: manufacturerMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://192.168.0.15:8200
      authpath: manufacturer-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/manufacturer-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/manufacturer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretgitprivatekey: secret/credentials/manufacturer-net/git?git_password
      tls: false
    orderer:
      address: orderer1.supplychain-net:7050
    chaincode:
      name: supplychain
      version: 1
      maindirectory: cmd
      repository:
        hostname: "innersource.accenture.com"
        git_username: "sownak.roy"
        url: innersource.accenture.com/scm/sow11/blockchain-automation-framework.git
        branch: develop
        path: examples/supplychain-app/fabric/chaincode_rest_server/chaincode/