---
dependencies:
  - role: "aws-cli"
    vars:
      aws_cli:
        bin_directory: "{{ bin_install_dir }}"
      aws_access_key: "{{ item.aws.access_key }}"
      aws_secret_key: "{{ item.aws.secret_key }}"