apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carriersaikumar-ambassador-job
  namespace: carriersaikumar-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carriersaikumar-ambassador-job
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/generate_ambassador_certs
    sourceRef:
      kind: GitRepository
      name: flux-saikumar
      namespace: flux-saikumar
  values:
    metadata:
      name: carriersaikumar-ambassador-job
      namespace: carriersaikumar-bes
    image:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullSecret: regcred
      pullPolicy: IfNotPresent
    network:
      tmtls: True
    node:
      name: carriersaikumar
      clientport: 8888
    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
      secretengine: secretsv2
      authpath: besucarriersaikumar
      rootcasecret: data/carriersaikumar-bes/crypto/ambassadorcerts/rootca
      ambassadortlssecret: data/carriersaikumar-bes/crypto/carriersaikumar/tls
      role: vault-role
      serviceaccountname: vault-auth
      type: hashicorp
    subject:
      ambassadortls: CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB
    opensslVars:
      domain_name_pub: carriersaikumar.saikb.dev.aws.blockchaincloudpoc-develop.com
      domain_name_priv: carriersaikumar.carriersaikumar-bes
      domain_name_tessera: carriersaikumar-tessera.carriersaikumar-bes
    healthcheck:
      retries: 10
      sleepTimeAfterError: 2

