apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: partner-dtg
  annotations:
    flux.weave.works/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: ssh://git@innersource.accenture.com/sow11/blockchain-automation-framework.git
    ref: feature/bafdemo
  values:
    metadata:
      name: partner-dtg
      namespace: partner-ns
    organization:
      name: partner
    configmap:
      domainGenesis: |-
        -e 
