##############################################################################################
#  This Chart is a fork from https://github.com/digicatapult/inteli-demo/tree/main/helm/inteli-demo
#  Please update if needed
##############################################################################################

apiVersion: v2
name: dscp-frontend
appVersion: '2.1.1'
description: A Helm chart for inteli-demo
version: '2.1.1'
type: application
