##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# This task creates the Bootnode value file for node helm chart
- name: Create value file for bootnode
  include_tasks: nested_main.yaml
  vars:    
    storageclass_name: "{{ item.cloud_provider }}storageclass"
    external_url: "{{ item.external_url_suffix }}"
    vault: "{{ item.vault }}"
    git_url: "{{ item.gitops.git_url }}"
    git_branch: "{{ item.gitops.branch }}"
    org: "{{ item }}"
    docker_url: "{{ network.docker.url }}"
    charts_dir: "{{ item.gitops.chart_source }}"
    values_dir: "{{playbook_dir}}/../../../{{item.gitops.release_dir}}/{{ item.name | lower }}"
    image: "{{ network.config.node_image }}"
    command: "{{ network.config.command }}"
    role: "full"
    bootnode_data: "{{ network.config.bootnodes }}"
  loop: "{{ peers }}"
  loop_control:
    loop_var: peer
  when: peer.type == 'bootnode'
