apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIBKsiLTXwBlZOw31HMPh4IfumRnw7DEPY9bgncS2zLVdEqheCqVeCqJeCngKWggBEAEaBgjR
      mpCaBiIKc3lzY2hhbm5lbCpAOWE5NGM2MWM0YWYyMTAwOTZjNWI2ODdmOGJlZjRiYTg5ODBmYmRi
      OGZlZTk0OGZhODJkNDM2MmQyMzM3NzNhZBIaEhj2iQ1KIEA07XPrqHdLqrkJjoRc1y9HutsSpV0K
      ol0Sn10SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVWXZMVmxxRkRvQXFUalVMdlhKclFkSDBJSVpJd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURFd01USXdNelEzV2hjTk1qVXdOek13TVRJd016UTNX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJPZEtZ
      Q3Y4d2pvWVVMQ3BzejNhYTkzeFFMcTZiOG1UQ2VXSkpGeEtrMUMxa040OGJCbWkKVys0YitnelJo
      anJKWWZFNUFRVHRWTVNLWmljRHFXYU9IeXFqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU2J2WmdsaFRERmpRSWtxZUVsS0NrVjVv
      RFdrakFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlBS25vblJUb2kwQ1FTS2JkK1RVcWZNY2FzSnhz
      L3hsZDdta0dlWU1EZ3kKZHdJZ0pGL1VlR1dFTTI2ZGtYVTJzQ2hGMjZBTXVIcnFSaFdmNUlMSGZF
      NzA5MXc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9lZ0F3SUJBZ0lVWEdyYTJOdkIzNjJuWFBGVXpMMmJtT29rUHhFd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURFd01USXdPREF3V2hjTk1q
      TXhNREV3TVRJeE16QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFTEYyekVmUHdudHZPbXBMLzE4dGQreHZyY2RF
      ZnEySTMKOTVhbTJLZ3lzbWRPMXhGSlFKb3g1TzVkV0lhUHJmUXRPbk1mVjR0ZGJ5TWZyN0p6WDcy
      WVVxT0NBUk13Z2dFUApNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTQjlLUnBFTGMwCjBGTTJ4TXppNlE4cklkb0FzVEFmQmdOVkhTTUVHREFXZ0JT
      YnZaZ2xoVERGalFJa3FlRWxLQ2tWNW9EV2tqQWoKQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kx
      a09EVTNZemRtTnpjdFp6aHJPSG93Z1lrR0NDb0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1G
      aVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkds
      aGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdO
      b1lXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05J
      QURCRgpBaUVBOWlyUVNRZnRHVkVod1djWVlqMnF3emJzWUpOTzUzaEl2S1FFa3laZEtYTUNJQ1JV
      aWZqS3JNcXo1akNCCjMxczFsdHl6QXlTMGpSM01KV0VENkltN1NhUWEKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIvekNDQWFhZ0F3SUJBZ0lVWXZMVmxxRkRvQXFUalVMdlhKclFkSDBJSVpJd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURFd01USXdNelEzV2hjTk1qVXdOek13
      TVRJd016UTNXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJPZEtZQ3Y4d2pvWVVMQ3BzejNhYTkzeFFMcTZiOG1UQ2VXSkpGeEtrMUMxa040OGJCbWkK
      Vys0YitnelJoanJKWWZFNUFRVHRWTVNLWmljRHFXYU9IeXFqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU2J2WmdsaFRERmpRSWtx
      ZUVsS0NrVjVvRFdrakFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlBS25vblJUb2kwQ1FTS2JkK1RV
      cWZNY2FzSnhzL3hsZDdta0dlWU1EZ3kKZHdJZ0pGL1VlR1dFTTI2ZGtYVTJzQ2hGMjZBTXVIcnFS
      aFdmNUlMSGZFNzA5MXc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVh
      ZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIW
      EgwKCgoGVjFfNF8yEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4ERLtEQoIZXRjZHJhZnQS
      4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlEQXpDQ0FxbWdBd0lCQWdJVU9NMHEwaHZpSHZNSUVDckxEUGM5M1RUVUUrWXdD
      Z1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURW
      UVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1ERXdNVEl3T0RBd1doY05N
      ak14TURFd01USXhNekF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVO
      VEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxF
      d2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpa
      WFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRzRERTM2JocXl3WDZkN3dIVysx
      cXRQSGMwCkVHdGtsQ25wNEJ4Nko4QlRCa2lCd2UwNk1NU1BJemljVFVrTFNRVE4xTjQyODVZQ1NG
      Y3ViQ0NmUmx5K280SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01C
      UUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERn
      UVdCQlFTTTB0R3EvTmJSMDkwdWdvd0drOWhpcHZWCnZqQWZCZ05WSFNNRUdEQVdnQlNidlpnbGhU
      REZqUUlrcWVFbEtDa1Y1b0RXa2pBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JI
      bGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0ND
      b0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFH
      WXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3
      aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU1B
      VHBOS0kzVDNDT256aApIdWN0S1VRdU90aG9OTG1jLzVUMGk1YUczOWROQWlCUUd0TTVWWEdVak5h
      K3pOUkliREJqenp4SlFUby9oYmRRCkt3YWc5czc0aEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxbWdBd0lCQWdJVU9N
      MHEwaHZpSHZNSUVDckxEUGM5M1RUVUUrWXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0Rn
      WURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      dwpIaGNOTWpJeE1ERXdNVEl3T0RBd1doY05Nak14TURFd01USXhNekF3V2pCeE1Rc3dDUVlEVlFR
      R0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFR
      S0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFN
      QkJ3TkNBQVRzRERTM2JocXl3WDZkN3dIVysxcXRQSGMwCkVHdGtsQ25wNEJ4Nko4QlRCa2lCd2Uw
      Nk1NU1BJemljVFVrTFNRVE4xTjQyODVZQ1NGY3ViQ0NmUmx5K280SUIKTURDQ0FTd3dEZ1lEVlIw
      UEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpB
      TUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlFTTTB0R3EvTmJSMDkwdWdvd0drOWhpcHZW
      CnZqQWZCZ05WSFNNRUdEQVdnQlNidlpnbGhUREZqUUlrcWVFbEtDa1Y1b0RXa2pBL0JnTlZIUkVF
      T0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJs
      ZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWht
      TGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEps
      Y2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3
      Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU1BVHBOS0kzVDNDT256aApIdWN0S1VRdU90aG9OTG1j
      LzVUMGk1YUczOWROQWlCUUd0TTVWWEdVak5hK3pOUkliREJqenp4SlFUby9oYmRRCkt3YWc5czc0
      aEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1p
      bnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4S
      BAoCMnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0
      ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIa
      BkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1p
      bnMSwy8KC0NvbnNvcnRpdW1zErMvEuguChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0Szi4SuxcKD21h
      bnVmYWN0dXJlck1TUBKnFxqvFQoDTVNQEqcVEpwVEpkVCg9tYW51ZmFjdHVyZXJNU1AShgYtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFnSVVHbzgxMWJtczFWZDI2
      R0E4b2xQSVhxSHhyaGN3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5Z
      VzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdI
      aGNOTWpJeE1ERXdNVEl3TkRVMVdoY05NalV3TnpNd01USXdORFUxV2pCa01Rc3dDUVlEVlFRRwpF
      d0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJn
      TlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNt
      VnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJIaHVBb1NHejhWckha
      NDNPeUdXR2QrTC9vbmZNZGZnTmxCVQpEL2E4aWwyR1BLQnp6K2x5NjhPWmgyYjMwSGp5dzZIYUJl
      QWsxRWVqc00xQjhNL3FxUStqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUzAxUDVpUmdJZVJKTGoKVlpLUEI5S2JaMkhNWERBS0Jn
      Z3Foa2pPUFFRREFnTkpBREJHQWlFQW9zcFI4bTcxVmlucWhEZGFvWlhaNVI4aQpsaDZZaHAvRGJY
      OXkybGlUMHUwQ0lRQ0ZNTlJZZXZ1U251VW44Z21HVDRKYzFmNis5UzJRMlN6aU5XY3RwQmxWCjZn
      PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJREVEQ0NBcmVnQXdJQkFnSVVFdHYyaTR0RDlyM2JyNTl3VDFtb2lvYVhiMk13Q2dZSUtv
      Wkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJn
      TlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1ERXdNVEl4TURBd1do
      Y05Nak14TURFd01USXhOVEF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFjVEVU
      UTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJeEl6
      QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZRFZR
      UUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29a
      SQp6ajBEQVFjRFFnQUV6VW55QWxUSWpFMEtqN3I4a2svNmdMSlZVdUI1ZGxmblBTaG5JY2VGOEVG
      bEJQbG1Zc2NMCkZRNzgxYUtSNjN6TEVRQ295aGZCVHAzd21XVjAvQncrZHFPQ0FTSXdnZ0VlTUE0
      R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNPbDNx
      Rmh0d0pPV0hJVVFVNlZQalpoSE9hekRBZgpCZ05WSFNNRUdEQVdnQlMwMVA1aVJnSWVSSkxqVlpL
      UEI5S2JaMkhNWERBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAzTm1Sak5qazROR1JrTFdk
      NlpuUnVNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWwwSWpv
      aWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9pYldG
      dWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVkV1po
      ClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFE
      QWdOSEFEQkUKQWlBV25PMEV2azhWWk01SytBTjdqZklJL1Z6cFZWWFY2MlRZWG1yMHg4R00rd0ln
      WmN5K25BMEZ1MjRQM2xLbAplaFJpUUQvZi9hdktXNXArc2VnYVc0Tlh5YTg9Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqGBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDRFRDQ0FiS2dBd0lCQWdJVUdvODExYm1zMVZkMjZHQThvbFBJWHFIeHJoY3dDZ1lJ
      S29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQ
      TUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFh
      QmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4TURFd01USXdORFUx
      V2hjTk1qVXdOek13TVRJd05EVTFXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdH
      V25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04w
      ZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFH
      U000OUFnRUdDQ3FHU000OUF3RUhBMElBQkhodUFvU0d6OFZySFo0M095R1dHZCtML29uZk1kZmdO
      bEJVCkQvYThpbDJHUEtCenorbHk2OE9aaDJiMzBIanl3NkhhQmVBazFFZWpzTTFCOE0vcXFRK2pR
      akJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWRE
      Z1FXQkJTMDFQNWlSZ0llUkpMagpWWktQQjlLYloySE1YREFLQmdncWhrak9QUVFEQWdOSkFEQkdB
      aUVBb3NwUjhtNzFWaW5xaERkYW9aWFo1UjhpCmxoNllocC9EYlg5eTJsaVQwdTBDSVFDRk1OUlll
      dnVTbnVVbjhnbUdUNEpjMWY2KzlTMlEyU3ppTldjdHBCbFYKNmc9PQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tChoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoP
      bWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEK
      D21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIR
      Cg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRIT
      Cg9tYW51ZmFjdHVyZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMSshYKCmNhcnJpZXJNU1ASoxYavxQK
      A01TUBK3FBKsFBKpFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlCK0RDQ0FaNmdBd0lCQWdJVUxLaDR1WWdiYzBQMHMyWnN3Zk1LdEN0cGRzUXdDZ1lJS29aSXpq
      MEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allT
      NWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV3TVRBeE1qQTJNREJhRncweU5UQTNNekF4TWpBMk1E
      QmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJB
      Y01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVky
      RnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVNOeFVqUGJF
      NnJnR0JaMUFQQlBFcC9yeXhkeHN2Wm5Sb3BkcEh3c0dSMWtoRjVoUjBFYTRoYXBwclQxdWNRCjdv
      Z3RVUVowMnlPdjU1bFQxcEpyRHVaY28wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFV
      ZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVOVg0eXd4ZjVrYmhCRVMweExiWHlPU2Y2bklj
      d0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBTmtyZEVvbnl1ZVpTY092QWNHUXhVUDcvclI1Qlhj
      QnFkMWo1ZWkybWxKTUFpQUJkV3J1ClAreDlrWlpDcm1PVEh5Y0UyQU1WaW1CVUZXMUlwWlRHa1ky
      RnlRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoisggtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQzdUQ0NBcFNnQXdJQkFnSVVjZ2d1NW1oTGs4ejVjM1RUMk13ZEJQYlBzTGN3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFR
      RERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFd01UQXhNakV5TURCYUZ3MHlNekV3TVRB
      eE1qRTNNREJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0
      eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYlds
      dU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kx
      dVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUUJKZ0djcG1QM0xQUStCUmEr
      ZFp0OApHcEZEYVRWazNhd1hUZUM0RGdocjkzNnB2NW9jWW1DOG1HMVYxdE9pOUNxQVBON1B4RmRu
      TUVpSXdBSU8yOEFCCm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VC
      L3dRQ01BQXdIUVlEVlIwT0JCWUUKRkhxbFpHNmdkTGpiMTM2eTlRUStndjlldTFidU1COEdBMVVk
      SXdRWU1CYUFGUFYrTXNNWCtaRzRRUkV0TVMyMQo4amtuK3B5SE1DUUdBMVVkRVFRZE1CdUNHV05o
      TFhSdmIyeHpMVFUyTkRWa1pEZGlPRGd0Y2pkME5uY3dnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpo
      ZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdp
      YUdZdVFXWm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxF
      SWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdD
      Z1lJCktvWkl6ajBFQXdJRFJ3QXdSQUlnS1lkaUxZQ0dieHFxcXZqRjFEcWxGcllnZUlNQmtCOGNj
      MWdUU3ZRT29hZ0MKSUdNNlN0cTlDRS9nRWx2VDdmcW5XSis3NWFrcFZ1RWZTdEFUcVFBazFOWmMK
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVTEtoNHVZZ2JjMFAwczJac3dmTUt0
      Q3RwZHNRd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlN
      UmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXdNVEF4TWpBMk1EQmFG
      dzB5TlRBM016QXhNakEyTURCYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1i
      MjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApN
      QlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BR
      TUJCd05DCkFBU054VWpQYkU2cmdHQloxQVBCUEVwL3J5eGR4c3ZablJvcGRwSHdzR1Ixa2hGNWhS
      MEVhNGhhcHByVDF1Y1EKN29ndFVRWjAyeU92NTVsVDFwSnJEdVpjbzBJd1FEQVBCZ05WSFJNQkFm
      OEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVU5WDR5d3hmNWti
      aEJFUzB4TGJYeU9TZjZuSWN3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJaEFOa3JkRW9ueXVlWlNj
      T3ZBY0dReFVQNy9yUjVCWGNCcWQxajVlaTJtbEpNQWlBQmRXcnUKUCt4OWtaWkNybU9USHljRTJB
      TVZpbUJVRlcxSXBaVEdrWTJGeVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5z
      IjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoG
      QWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5k
      b3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVh
      ZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAK
      FUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxotChlCbG9ja0Rh
      dGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMS
      OhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zGiYKEEhhc2hpbmdBbGdv
      cml0aG0SEhIICgZTSEEyNTYaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFk
      bWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
