apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIA7yj9rtq1A+u+NscHPqfxAovQQvD2OJ2X+lxKpRJoIHEpJeCo9eCoxeCngKWggBEAEaBgi3
      opOaBiIKc3lzY2hhbm5lbCpAMGNlMDUyN2MzMjNkZmJmMzE3NzJkMjcxYTJiODdkZjc5YmE4MWRj
      Y2JmM2NjODQyODgzYzVkNWQ1YTA0MzEzZRIaEhjQ8c0PTBbYziAbrRttPhy6b4qGJhqYrn4Sj10K
      jF0SiV0SiysKB09yZGVyZXIS/yoSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVUTk0dkQ4YkJBRnVUOTlLSE1YTXh3cFVueTFFd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURFeE1ERTFPVEl5V2hjTk1qVXdOek14TURFMU9USXlX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJOdktt
      elptQ2U3VmVmdjFMQU5YVW41Q0R2c3dyVGE0dmZFL1p2U3YvRWtud2wzV3NzeU4KbnU3b1NVb2k1
      djlCRDllazdFU2ZaWHdJWHdIRVlYMHNXYVNqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVE9yK1hVeE9PNDhDcDUreGNSaGZaZjVN
      RGJjVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCRXpSYkFyRXhUSFk0SWJMcnQwTkZRS1V5alVr
      SGk1dXdIZTNtOXd1eUEKQUFJaEFKT3ZRNTI3aHN3SUZMUGZCR1RPU05CaTdJRkFyS2lqRFVYaVAw
      alpITWxhCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9lZ0F3SUJBZ0lVTFNaNWRNNnpmWGdQUk1OOUJaZnpaT0MxRDlZd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURFeE1ESXdOVEF3V2hjTk1q
      TXhNREV4TURJeE1EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFcDllNzJRM0VURnZ0MEhWQXp6ZUg4Sy9adWp6
      SDl0ZjkKZGpTTmJQSFl2QXNCU0haMWhyNkVQMHRPVUlHdWRJbjBnMWZ5TlYxRFZRTFdWbFY5ZDJM
      WFVxT0NBUk13Z2dFUApNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRL3lhZVlWYURxCitxNnI1d3M0WGpldFBFTytkakFmQmdOVkhTTUVHREFXZ0JU
      T3IrWFV4T080OENwNSt4Y1JoZlpmNU1EYmNUQWoKQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kx
      a09EVTNZemRtTnpjdFltaHhPSGN3Z1lrR0NDb0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1G
      aVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkds
      aGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdO
      b1lXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05J
      QURCRgpBaUVBbk9JNFRvdEo4bW14ZG1sa1Q2RWFCN2dHZnhLRmZTemcvQzduR2xaSGh3Y0NJRDdw
      UGpDMEhzVmd4Tlh4CnNwOHJWWkI5akdsblhvQ0xkbGo3Wk9pdnZWUFcKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVUTk0dkQ4YkJBRnVUOTlLSE1YTXh3cFVueTFFd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURFeE1ERTFPVEl5V2hjTk1qVXdOek14
      TURFMU9USXlXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJOdkttelptQ2U3VmVmdjFMQU5YVW41Q0R2c3dyVGE0dmZFL1p2U3YvRWtud2wzV3NzeU4K
      bnU3b1NVb2k1djlCRDllazdFU2ZaWHdJWHdIRVlYMHNXYVNqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVE9yK1hVeE9PNDhDcDUr
      eGNSaGZaZjVNRGJjVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCRXpSYkFyRXhUSFk0SWJMcnQw
      TkZRS1V5alVrSGk1dXdIZTNtOXd1eUEKQUFJaEFKT3ZRNTI3aHN3SUZMUGZCR1RPU05CaTdJRkFy
      S2lqRFVYaVAwalpITWxhCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVh
      ZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0
      aW9ucxIIGgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGoIS
      Cg1Db25zZW5zdXNUeXBlEvAREuURCghldGNkcmFmdBLYEQrBEQoYb3JkZXJlcjEuc3VwcGx5Y2hh
      aW4tbmV0EIo3Gs8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBakNDQXFtZ0F3SUJB
      Z0lVZU1EYjgweW9HK1FRK2duOHJEcnJFNzJEU2Jvd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJp
      MXVaWFF3CkhoY05Nakl4TURFeE1ESXdOVEF3V2hjTk1qTXhNREV4TURJeE1EQXdXakJ4TVFzd0NR
      WURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0Rn
      WURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4
      aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CQndOQ0FBUUU4V3M5TlorNzFXeTJhblRINzE5RmE4ZUgKcEd0clB4ZUhQV1JqRlhGNEVx
      YjkvUzBsLy9EOHhTbDNhRklRakptN1l5MFdqalRKRFRtQVFDVW5tUTdMbzRJQgpNRENDQVN3d0Rn
      WURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJR
      Y0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVFdaMFBXZVppd1l2WTNmTWNUdjMv
      UW1jdXUKSmpBZkJnTlZIU01FR0RBV2dCVE9yK1hVeE9PNDhDcDUreGNSaGZaZjVNRGJjVEEvQmdO
      VkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJ
      eExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpw
      N0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNK
      a1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJ
      aWZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdBbWRpSms1anpqeVBWcldFCkRWaHhqSWhlUzZq
      U3lVL0ZZWUFCejZmWmNaa0NJR2sycXh3dmd0eU9yV0NEWVJSSzRHNmg2RmlMdTUxY3UzR2YKOThD
      T1Q3QTQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoizwgtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJREFqQ0NBcW1nQXdJQkFnSVVlTURiODB5b0crUVErZ244ckRyckU3MkRTYm93Q2dZ
      SUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFR
      RERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXhNREV4TURJd05UQXdXaGNOTWpN
      eE1ERXhNREl4TURBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRB
      dkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdk
      dmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhR
      d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRRThXczlOWis3MVd5MmFuVEg3MTlG
      YThlSApwR3RyUHhlSFBXUmpGWEY0RXFiOS9TMGwvL0Q4eFNsM2FGSVFqSm03WXkwV2pqVEpEVG1B
      UUNVbm1RN0xvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFH
      Q0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FX
      QkJUV1owUFdlWml3WXZZM2ZNY1R2My9RbWN1dQpKakFmQmdOVkhTTUVHREFXZ0JUT3IrWFV4T080
      OENwNSt4Y1JoZlpmNU1EYmNUQS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxq
      YUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29E
      QkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1
      Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lh
      R1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ0FtZGlK
      azVqemp5UFZyV0UKRFZoeGpJaGVTNmpTeVUvRllZQUJ6NmZaY1prQ0lHazJxeHd2Z3R5T3JXQ0RZ
      UlJLNEc2aDZGaUx1NTFjdTNHZgo5OENPVDdBNAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChIS
      CgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZB
      ZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggD
      EgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMa
      BkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoGQWRtaW5zErUvCgtD
      b25zb3J0aXVtcxKlLxLaLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsAuErEXCg9tYW51ZmFjdHVy
      ZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEGLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVWFFteFdIb0JGKzloYzlNdzlIZStu
      aHpUZ2lrd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01C
      bHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpk
      SFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhN
      REV4TURJd01ESTVXaGNOTWpVd056TXhNREl3TURJNVdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBN
      QTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpE
      RTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGRE
      QlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCR2tlOWpFeGdzWjlPT3gzeldpZ0Fy
      ZnM2cWh4akV5NWplNVcKaVFTSzhteTA4cVpsVVBxRlVTNGpEQnY0SEdld2owNEVjMFpRRXpQQ0cx
      SWdvZVUyWDFxalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFn
      R21NQjBHQTFVZERnUVdCQlJEcGZMaFNlYXNCRzhxCjlhNjVRMGY1a2I3ZXp6QUtCZ2dxaGtqT1BR
      UURBZ05JQURCRkFpRUE4azVpS1N4bEVPenNFYUFxWmYvL0tPcloKczJsNDB0NzdJSWxxbFk5WTgy
      TUNJQ2VGVmtTdEJlTTVWWWtoVkdPNUFhYytDWDU1WThlKzA0c0pZTlV6WWt6VgotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERVRDQ0Fy
      ZWdBd0lCQWdJVUdjY2wwekxVWGtaemMwemdXQXFoeWJrL2xVWXdDZ1lJS29aSXpqMEVBd0l3ClpE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25W
      eWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0x
      aGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4TURFeE1ESXdOakF3V2hjTk1qTXhNREV4TURJ
      eE1UQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xqTTRMemd1TlRR
      dlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJnTlZCQXNUQldG
      a2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERCWkJaRzFwYmtC
      dFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERBUWNEUWdB
      RTJZb1NFZHozZXpVTjdlUlJRWGRHZTVPUXJpRzFsayttWDVwNVEvZS9vTVlsT0ZRRGk5MXoKSlZq
      UFNsZjRhWjRtMU1MK2VxdGhVZWpuZHlLMVBwLy95YU9DQVNJd2dnRWVNQTRHQTFVZER3RUIvd1FF
      QXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUXZtN0hLSS9DMVBBVmtBa2xi
      YTZ4dTVNNkhrREFmCkJnTlZIU01FR0RBV2dCUkRwZkxoU2Vhc0JHOHE5YTY1UTBmNWtiN2V6ekFr
      QmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNObVJqTmprNE5HUmtMVGt5Y1hJMU1JR1hCZ2dx
      QXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZr
      YldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFdaaFkzUjFjbVZ5
      SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNSMWNtVnlMVzVs
      ZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRgpBaUVB
      ODFnRmpJZDFXK2VsNUl5T1lsenhxZmRsZDhRcGJKckhpN3RIbEhzYnVJY0NJQi9rYmJnOHVrRnY2
      SHpmCmh4b0dsVlc3RXNvSXBRbDJwNkgrWk0rb3RLMG4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEREND
      QWJLZ0F3SUJBZ0lVWFFteFdIb0JGKzloYzlNdzlIZStuaHpUZ2lrd0NnWUlLb1pJemowRUF3SXcK
      WkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dX
      blZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhM
      bTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNREV4TURJd01ESTVXaGNOTWpVd056TXhN
      REl3TURJNVdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdE
      UVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dB
      MVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdT
      TTQ5QXdFSEEwSUFCR2tlOWpFeGdzWjlPT3gzeldpZ0FyZnM2cWh4akV5NWplNVcKaVFTSzhteTA4
      cVpsVVBxRlVTNGpEQnY0SEdld2owNEVjMFpRRXpQQ0cxSWdvZVUyWDFxalFqQkFNQThHQTFVZApF
      d0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlJEcGZMaFNl
      YXNCRzhxCjlhNjVRMGY1a2I3ZXp6QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUE4azVpS1N4bEVP
      enNFYUFxWmYvL0tPcloKczJsNDB0NzdJSWxxbFk5WTgyTUNJQ2VGVmtTdEJlTTVWWWtoVkdPNUFh
      YytDWDU1WThlKzA0c0pZTlV6WWt6VgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5z
      IjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZB
      ZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoG
      QWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1Aa
      BkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJNU1AQ
      ARoGQWRtaW5zKgZBZG1pbnMSrhYKCmNhcnJpZXJNU1ASnxYauxQKA01TUBKzFBKoFBKlFAoKY2Fy
      cmllck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lCQWdJ
      VVA4SC9jMHZsMGxybTdLbXoxb3ZkamFXQVJYTXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFV
      RUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJB
      d0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFl
      RncweQpNakV3TVRFd01qQXhNelZhRncweU5UQTNNekV3TWpBeE16VmFNRm94Q3pBSkJnTlZCQVlU
      QWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRH
      QTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFU
      QmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFHSDBFRHBqaFhqS3VGY1NrdWdJbExPRWds
      c1o1cEF1NlpRUXZ2TE5WOHhENmp6Ky9LUjZpYlBGcktwcTNBCnV5UUNnNndlZ3dMUitNaFpKWk52
      RVNaeW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFk
      QmdOVkhRNEVGZ1FVZWx0T3BoQ1pMdWFUMktjdVBuSVo0N1piZ0djd0NnWUlLb1pJemowRQpBd0lE
      UndBd1JBSWdIZDFVVEtwUGh0MUZ1NkdpMWx2Mmx5dXZvbGtEZGErWTVIYmtLTEx3UFdjQ0lBL0hT
      dHZLCndPbFZwbWpQRlY0Z2JwSTFlc1UyUEh0MzlUVG9BMjFXVjJQMAotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCiK2CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDN2pDQ0FwU2dBd0lC
      QWdJVVY5Q0ZGWWZ4TXZobHNoemVFRTBkRjNjRnd4RXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxk
      REFlRncweQpNakV3TVRFd01qQTNNREJhRncweU16RXdNVEV3TWpFeU1EQmFNSGd4Q3pBSkJnTlZC
      QVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZC
      QW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVDeE1IWTJGeWNtbGxj
      akVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJC
      Z2dxaGtqT1BRTUJCd05DQUFTcXFhdG1wZzRuTkFJenptb1hnWFBxCnVONUtZSTNYYzFHdlJXdzNu
      d1QrMTZZbTBTWFUyTWx3em91cXFoWDQyVFRzU2RHc0FHSFZnTlhoaHJhbzh1V0IKbzRJQkdEQ0NB
      UlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRQpG
      R1pCN3lRaWRBdkR5V09XMWpXaVBzOFVIQ2VoTUI4R0ExVWRJd1FZTUJhQUZIcGJUcVlRbVM3bWs5
      aW5MajV5CkdlTzJXNEJuTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxUVTJORFZrWkRkaU9E
      Z3RjWGc1ZURnd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5SmhZbUZqTG1sdWFY
      UWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFXeHBZWFJwYjI0aU9p
      SmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFXNUFZMkZ5Y21sbGNp
      MXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpqMEVBd0lEU0FBd1JR
      SWhBTXdRU2tIQTJzbXNtWjRRazYxeDdSN0t0QmJ2RDV5a21KRy9PaVAzcDRtYwpBaUJTWUNCT3M5
      VHh2WXhHcXk4QTZNbks3aWJHYUthNTFuWVRONHd2YVBwRzRRPT0KLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUI5ekNDQVo2Z0F3SUJBZ0lVUDhIL2MwdmwwbHJtN0ttejFvdmRqYVdBUlhNd0NnWUlLb1pJemow
      RUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1
      allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXdNVEV3TWpBeE16VmFGdzB5TlRBM016RXdNakF4TXpW
      YU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFj
      TUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJG
      eWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUUdIMEVEcGpo
      WGpLdUZjU2t1Z0lsTE9FZ2xzWjVwQXU2WlFRdnZMTlY4eEQ2anorL0tSNmliUEZyS3BxM0EKdXlR
      Q2c2d2Vnd0xSK01oWkpaTnZFU1p5bzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVk
      RHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVlbHRPcGhDWkx1YVQyS2N1UG5JWjQ3WmJnR2N3
      Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ0hkMVVUS3BQaHQxRnU2R2kxbHYybHl1dm9sa0RkYStZ
      NUhia0tMTHdQV2NDSUEvSFN0dksKd09sVnBtalBGVjRnYnBJMWVzVTJQSHQzOVRUb0EyMVdWMlAw
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAES
      GhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggS
      BggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAES
      AggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQ
      Eg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5
      EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMq
      Fy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8zEgAa
      BkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tE
      YXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2Vz
      EjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRt
      aW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMS
      CQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZB
      ZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
