apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aictevalidator2validator-node
  namespace: aicte-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: aictevalidator2validator-node
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_validator
    sourceRef:
      kind: GitRepository
      name: flux-prod
      namespace: flux-prod
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://9ea98f074fc4df54096a33c6b844f08f294bb74c1428b54dfd738b4fdf3c9071966219a941b6fd775a16035daab57e106d7345f0628d9c69f5b1e0c8b01cdc70@validator1.app.bharatblockchain.io:15010"
      - "enode://b5693f0a4356fd22ffc57ed43b1bb7b311d9f1ec717898ccf40c9af0069191d906c612cf9deeb08852168600705cdfc4ae57bd2ba9fd764911c67ca02183ea39@validator2.app.bharatblockchain.io:15012"
      - "enode://391f21a19287508d5d9639ec9c7f111593656aea2ae0b092851fb1dac4f23c875b7a382df942ca6ab2e1407a4df7a3bea5b94aa48bf33b01cc5f79906fb5a8ec@validator3.app.bharatblockchain.io:15014"
      - "enode://d582f23467fb547e8b0464c6c6338bb3b910af483c9cf62ce49b90db3d209d499031516749607a39a9a601107e6992a2ec6c0fb49cb38e9cd58be482e6567305@validator4.app.bharatblockchain.io:15016"
      - "enode://1e97f1ffa4d9b16779c454016b0a43478fcbe9c7a4a3e58b757d4a7c1a4f1f5ed85bcbafa048a4c2dc59c9485e97704d874b022e44132528409a6788182ee2c7@ids.app.bharatblockchain.io:15020"

    metadata:
      namespace: aicte-bes
      labels:

    ambassador:
      external_url_suffix: app.bharatblockchain.io

    liveliness_check:
      enabled: false
    proxy:
      provider: ambassador
      external_url: aicte.app.bharatblockchain.io
      p2p: 15012
      rpc: 15013

    images:
      node: hyperledger/besu:21.10.6
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      pullPolicy: IfNotPresent

    node:
      name: validator2
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://afaa81f5113c849ca8e7cad72f262df9-2626065.ap-south-1.elb.amazonaws.com:8200
      secretprefix: secretsv2/data/aicte-bes/crypto/validator2
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besuaicte

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMjMsCiAgICAiYmVybGluQmxvY2siOiAwLAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiA0CiAgICB9CiAgfSwKICAibm9uY2UiOiAiMHgwIiwKICAidGltZXN0YW1wIjogIjB4NThlZTQwYmEiLAogICJnYXNMaW1pdCI6ICIweDFBNUYxMzIzQkRBMzA4MDAiLAogICJkaWZmaWN1bHR5IjogIjB4MSIsCiAgIm1peEhhc2giOiAiMHg2Mzc0Njk2MzYxNmMyMDYyNzk3YTYxNmU3NDY5NmU2NTIwNjY2MTc1NmM3NDIwNzQ2ZjZjNjU3MjYxNmU2MzY1IiwKICAiY29pbmJhc2UiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAiYWxsb2MiOiB7CiAgICAiYTc1NzgzRTdhNDkyZjllRDljNTJiMzFjNkE2MUFERmRGNjJBODQxMSI6IHsKICAgICAgImJhbGFuY2UiOiAiMHhhZDc4ZWJjNWFjNjIwMDAwMCIKICAgIH0sCiAgICAiNzUwM2E3OTRBNTk4MTcyNkVDMjdEMjZGMjI0N0RjMjYxZTc2NjM0NCI6IHsKICAgICAgImJhbGFuY2UiOiAiOTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiCiAgICB9LAogICAgIjU5MDAxQUVGRUZDRDcyQWMyNUNGYjM1RTAwQmFlZmM4NDhhQmRGODYiOiB7CiAgICAgICJiYWxhbmNlIjogIjkwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgogICAgfQogIH0sCiAgImV4dHJhRGF0YSI6ICIweGY4N2VhMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBmODU0OTRlZTM4MGFiNzlhMTA2YzRkZTE3NDEyZThhNDRmOGY5MzI4NWFjM2JlOTRiMzAzMTVhYTU4YTFjYmVjN2I2MjA3MTU5YTQ4YjZiODMyNTlhZDAwOTRiZTBhYjY2MTMxN2RmZDdjN2NkOTVlN2MxNDQ0Y2Q1MTk4ZjU1MGViOTQ3MDljNTUxZGEzMTQxMmY3NTBlOTAwM2MxMzYwMTFmNWJmNWY0MTgzODA4NDAwMDAwMDAwYzAiCn0=
