version: 2.1
# commands are used to group common steps and enable re-use
commands:
  mvn_build:
    description: "Builds jar file using maven"
    parameters:
      build_path:
        type: string
        default: "."
      build_jar:
        type: string
        default: "doorman.jar"
    steps:      
      - run: 
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
            sudo apt-get install -y nodejs
      - run: 
          command: |
            cd << parameters.build_path >>
            mvn clean install
  docker_push:
    description: "Builds docker image and pushes to dockerhub"
    parameters:
      build_path:
        type: string
        default: "."
      image:
        type: string
        default: "hyperledgerlabs/doorman-linuxkit"
      tag:
        type: string
        default: "latest"
      tag_prefix:
        type: string
        default: ""
    steps:
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: ls -a << parameters.build_path >>/*
      # build and push Docker image
      - run: |
          cd << parameters.build_path >>
          docker build -t << parameters.image >>:<< parameters.tag_prefix >><< parameters.tag >> .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push << parameters.image >>:<< parameters.tag_prefix >><< parameters.tag >>
      - run: |
          echo $CIRCLE_TAG
          if [[ -z "$CIRCLE_TAG" ]]; then 
            echo "Not a tagged check-in";
          else
            docker tag << parameters.image >>:<< parameters.tag_prefix >><< parameters.tag >> << parameters.image >>:<< parameters.tag_prefix >>$CIRCLE_TAG;
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin;
            docker push << parameters.image >>:<< parameters.tag_prefix >>$CIRCLE_TAG;
          fi
  molecule:
    description: "Executes molecule test for ansible roles"
    parameters:
      role_path:
        type: string
        default: "."
      scenario:
        type: string
        default: "default"
    steps:  
      - run:
          name: Install molecule
          command: |
            docker --version
            python --version
            pip install --user 'molecule[docker]==3.0.2'
            pip install openshift
      - run: 
          name: Run molecule tests
          command: |
            export PATH=~/.local/bin/:~/bin:$PATH
            molecule --version
            cd << parameters.role_path >>
            mkdir tests
            export ANSIBLE_LOG_PATH=$PWD/tests/test-results.log
            molecule test -s << parameters.scenario >>
      - store_test_results:
          path: << parameters.role_path >>/tests

# Create jobs, so that a workflow can coordinate them.
jobs: 
  doorman_build: # Builds doorman jar file
    docker: # it uses the docker executor
      - image: circleci/openjdk:8-jdk-stretch
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls pulls code down from GitHub
      - mvn_build:
          build_path: "platforms/r3-corda/images/doorman"
          build_jar: "doorman.jar"
      - docker_push:
          build_path: "platforms/r3-corda/images/doorman"
          image: "hyperledgerlabs/doorman-linuxkit"
  networkmap_build: # Builds networkmap jar file
    docker: # it uses the docker executor
      - image: circleci/openjdk:8-jdk-stretch
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls pulls code down from GitHub
      - mvn_build:
          build_path: "platforms/r3-corda/images/networkmap"
          build_jar: "network-map-service.jar"
      - docker_push:
          build_path: "platforms/r3-corda/images/networkmap"
          image: "hyperledgerlabs/networkmap-linuxkit"
  corda_build: # Builds supplychain-corda docker images
    docker: # it uses the docker executor
      - image: circleci/openjdk:8-jdk-stretch
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls pulls code down from GitHub
      - run:
          name: Test cordapps
          command: |
            cd examples/supplychain-app/corda/cordApps_springBoot
            ./gradlew test
      - store_test_results:
          # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: examples/supplychain-app/corda/cordApps_springBoot/build/test-results/test
      - run:
          name: Build webapp
          command: |
            cd examples/supplychain-app/corda/cordApps_springBoot
            ./gradlew deployWebapps
      - store_artifacts: # Upload test results for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: examples/supplychain-app/corda/cordApps_springBoot/build/webapps
          when: always
      - docker_push:
          build_path: "examples/supplychain-app/corda/cordApps_springBoot"
          image: "hyperledgerlabs/supplychain_corda"
          tag_prefix: "springboot_"
      - docker_push:
          build_path: "examples/supplychain-app/corda/express_nodeJS"
          image: "hyperledgerlabs/supplychain_corda"
          tag_prefix: "express_app_"
  frontend_build: # Builds supplychain-frontend docker image
    docker: # it uses the docker executor
      - image: circleci/openjdk:8-jdk-stretch
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls pulls code down from GitHub
      - docker_push:
          build_path: "examples/supplychain-app/supplychain-frontend"
          image: "hyperledgerlabs/supplychain_frontend"
  fabric_build: # Builds supplychain-fabric docker images
    docker: # it uses the docker executor
      - image: circleci/openjdk:8-jdk-stretch
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls pulls code down from GitHub
      - docker_push:
          build_path: "examples/supplychain-app/fabric/chaincode_rest_server/rest-server"
          image: "hyperledgerlabs/supplychain_fabric"
          tag_prefix: "rest_server_"
      - docker_push:
          build_path: "examples/supplychain-app/fabric/express_nodeJs"
          image: "hyperledgerlabs/supplychain_fabric"
          tag_prefix: "express_app_"
  shared_test:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      PYENV_VERSION: 3.6.5
    steps:
      - checkout
      - molecule:
          role_path: "platforms/shared/configuration"
  shared_test_corda:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      PYENV_VERSION: 3.6.5
    steps:
      - checkout
      - molecule:
          role_path: "platforms/shared/configuration"
          scenario: "kubernetes-corda"
  shared_test_fabric:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      PYENV_VERSION: 3.6.5
    steps:
      - checkout
      - molecule:
          role_path: "platforms/shared/configuration"
          scenario: "kubernetes-fabric"
  shared_test_indy:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      PYENV_VERSION: 3.6.5
    steps:
      - checkout
      - molecule:
          role_path: "platforms/shared/configuration"
          scenario: "kubernetes-indy"
      

# Under the workflows: map, we can coordinate our two jobs, defined above.
workflows:
  version: 2
  shared:
    jobs:
      - shared_test
      - frontend_build:
          filters:      # frontend build only for develop branch and all tags
            branches:
              only:
                - develop
            tags:
              only: /.*/
  corda: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - shared_test_corda
      - doorman_build:
          filters:      # doorman build only for develop branch and all tags
            branches:
              only:
                - develop
            tags:
              only: /.*/
      - networkmap_build:
          filters:      # networkmap build only for develop branch and all tags
            branches:
              only:
                - develop
            tags:
              only: /.*/
      - corda_build:
        filters:      # corda build only for develop branch and all tags
          branches:
            only:
              - develop
              - circleci-project-setup
          tags:
            only: /.*/
  fabric: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - shared_test_fabric
      - fabric_build:
        filters:      # corda build only for develop branch and all tags
          branches:
            only:
              - develop
              - circleci-project-setup
          tags:
            only: /.*/
  indy: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - shared_test_indy
