
metadata:
  namespace: 

replicaCount: 1

image:
  repository: chary123/cplcb:latest
  pullPolicy: Always

service:
  type: LoadBalancer
  name: test
  port: 3000
  targetPort: 3000
  nodePort: 30001

container:
  name: test-hc

plugins: 
  confdir: /etc/plugin
  packageName: "@hyperledger/cactus-plugin-ledger-connector-besu"
  type: org.hyperledger.cactus.plugin_import_type.LOCAL
  action: org.hyperledger.cactus.plugin_import_action.INSTALL
  rpcApiHttpHost: http://validator1.app.minftnft.co.in:15011
  rpcApiWsHost: ws://validator1.app.mintnft.co.in:8546 
  instanceId: '12345678'
              
envs:
  authorizationProtocol: 'NONE'
  authorizationConfigJson: '{}'
  grpcTlsEnabled: 'false'

proxy:
  provider: "ambassador"
  external_url:
  rpcport: 15080
healthcheck:
  readinessthreshold:
  readinesscheckinterval:

# This section contains the storage information.
storage:
  storageclassname: 
  storagesize: 

vault:
  serviceAccountName: 
  address: 
  secretPrefix: 
  keyname: 
  tmdir: 
  tlsdir: 
  authpath: 
  role: 

