##############################################################################################
#  This Chart is a fork from https://github.com/digicatapult/vitalam-ipfs/tree/main/helm/vitalam-ipfs
#  Please update if needed
##############################################################################################
apiVersion: v2
name: vitalam-ipfs-node
appVersion: '2.0.2'
description: A Helm chart for vitalam-ipfs
version: '2.0.2'
type: application
