# Default values for nodechart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.\

#name of the node to create
nodeName:
#namespace where the pod will be created
metadata:
  namespace:
# replicacount of the deployment.
#Eg. replicaCount: 1
replicaCount:

# App parameters
frontend:
  # Servicetype on which the frontend service will be available
  serviceType:
  nodePorts:
    port:
    targetPort:
  # docker image link for the frontend app
  #Eg. image: docker.io/frontend:latest
  image:
  #pullpolicy of the image
  pullPolicy:
  #docker secret to be used for pulling image
  pullSecrets:
  # env variables that will be passed to the container
  env:
    webserver:
deployment:
  annotations: {}
ambassador:
  #Provide annotations for ambassador service configuration
  #Eg.   annotations: |-
  #            ---
  #            apiVersion: ambassador/v1
  #            kind: Mapping
  #            name: networkmap_mapping
  #            prefix: /
  #            service: network-map.default:8080
  #            host: networkmap-cluster7.blockchainkubepoc.com
  #            host_rewrite: networkmap-cluster7.blockchainkubepoc.com
  #            tls: networkmap_mapping_tlscontext
  #            ---
  #            apiVersion: ambassador/v1
  #            kind: TLSContext
  #            name: networkmap_mapping_tlscontext
  #            hosts:
  #            - networkmap-cluster7.blockchainkubepoc.com
  #            secret: networkmap-ambassador-certs
  annotations:
