apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: notarykd
  annotations:
    flux.weave.works/automated: "false"
  namespace: supplychainkd-ns
spec:
  releaseName: notarykd
  chart:
    path: platforms/r3-corda/charts/notary
    git: git@github.com:deepakkumardbd/blockchain-automation-framework.git
    ref: corda-checks-test
  values:
    nodeName: notarykd
    replicas: 1
    metadata:
      namespace: supplychainkd-ns
    image:
      containerName: adopblockchaincloud0502.azurecr.io/corda:4.1-linuxkit
      initContainerName: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: doormankd.rc.dev.aws.blockchaincloudpoc-develop.com
      networkmapCertAlias: networkmapkd.rc.dev.aws.blockchaincloudpoc-develop.com
    nodeConf:
      p2p:
        url: notarykd.supplychainkd-ns
        port: 10002
      ambassadorAddress: notarykd.rc.dev.aws.blockchaincloudpoc-develop.com:10010
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=Notary,OU=Notary,L=London,C=GB #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
            
      notary:
        validating: false
       
      detectPublicIp: false
      database:
        transactionIsolationLevel: READ_COMMITTED
        exportHibernateJMXStatistics: false
      dbUrl: notarykddb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://notarykddb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: https://networkmapkd.rc.dev.aws.blockchaincloudpoc-develop.com:8443
      doormanURL: https://doormankd.rc.dev.aws.blockchaincloudpoc-develop.com:8443
      compatibilityZoneURL:
      jarVersion: 4.1
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: notarykdoperations
          permissions: [ALL]

    cordapps:
      getcordapps: false

    volume:
      baseDir: /base/corda
    resources:
      limits: "1Gi"
      requests: "1Gi" 
    pvc:
      name: notarykd-pvc
      annotations: {}
      memory: 512Mi
      storageClassName: awsstorageclass

    service:
      name: notarykd
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
        targetPort: 10003 
      rpcadmin:
        port: 10005
        targetPort: 10005
         
    deployment:
      annotations: {}
    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:8200
      role: vault-role
      authpath: cordanotarykd
      serviceaccountname: vault-auth
      dbsecretprefix: notarykd/credentials/database
      rpcusersecretprefix: notarykd/credentials/rpcusers
      tokensecretprefix: notarykd/credentials/vaultroottoken
      keystoresecretprefix: notarykd/credentials/keystore
      certsecretprefix: notarykd/certs
      networkmapsecretprefix: notarykd/credentials/networkmappassword
      cordappsreposecretprefix: notarykd/credentials/cordapps

          
    healthcheck:
      readinesscheckinterval: 20
      readinessthreshold: 20
    ambassador:
      component_name: notarykd
      external_url_suffix: rc.dev.aws.blockchaincloudpoc-develop.com
      p2p_ambassador: 10010
      
