apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: provider-provider-endorser
  annotations:
    flux.weave.works/automated: "false"
  namespace: provider-ns
spec:
  releaseName: provider-provider-endorser
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: ssh://git@innersource.accenture.com/sow11/blockchain-automation-framework.git
    ref: feature/bafdemo
  values:
    metadata:
      name: provider-provider-endorser
      namespace: provider-ns
    network:
      name: baf
    image:
      name: provider
      repository: adopblockchaincloud0502.azurecr.io/indy-key-mgmt:0.3.0.0
      pullSecret: regcred
    vault:
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9000
      keyPath: provider.endorsers
      identity: provider-endorser
      auth_path: kubernetes-provider-admin-auth
    account:
      service: provider-admin-vault-auth
      role: rw
