metadata:
  namespace:
  #baf
  name:
  #indy-auth-job

network:
  name:

image:
  name:
  #indy-auth-job
  repository:
  #alpine:3.9.4

vault:
  address:
  #http://vault:8200
  keyPath:
  #provider.stewards
  identity:
  #my-identity
  auth_path:
  #kubernetes-baf-provider-admin-auth

account:
  service:
  # vault-auth-provider-agent-app
  role:
  # rw
