apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.peer.name }}
  namespace: {{ $.Values.metadata.namespace }}
  {{ if or $.Values.ambassador (and $.Values.service.loadBalancerType (eq $.Values.service.loadBalancerType "Internal")) }}
  annotations:
  {{ end }}
  {{ if $.Values.ambassador }}
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: TLSContext
      ambassador_id: {{ $.Values.ambassador.ambassador_id }}
      name: tls_context_{{ $.Values.peer.name }}_{{ $.Values.metadata.namespace }}
      hosts:
      - {{ $.Values.peer.name }}.{{ $.Values.metadata.namespace }}.{{ $.Values.ambassador.external_url_suffix }}
      secret: client-{{ $.Values.metadata.namespace }}-ambassador-certs
      alpn_protocols: h2
      ---
      apiVersion: ambassador/v1
      kind: TLSContext
      ambassador_id: {{ $.Values.ambassador.ambassador_id }}
      name: tls_context_{{ $.Values.peer.name }}_{{ $.Values.metadata.namespace }}_upstream
      secret: {{ $.Values.peer.name }}-{{ $.Values.metadata.namespace }}-ambassador-certs
      alpn_protocols: h2
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      ambassador_id: {{ $.Values.ambassador.ambassador_id }}
      tls: tls_context_{{ $.Values.peer.name }}_{{ $.Values.metadata.namespace }}_upstream
      grpc: True
      name: {{ $.Values.peer.name }}_{{ $.Values.metadata.namespace }}_mapping
      #headers:
      #  :authority: {{ $.Values.peer.name }}.{{ $.Values.metadata.namespace }}.{{ $.Values.ambassador.external_url_suffix }}:{{ $.Values.ambassador.port }}
      prefix: /
      rewrite: /
      service: {{ $.Values.peer.name }}.{{ $.Values.metadata.namespace }}:{{ $.Values.service.ports.grpc.clusteripport }}
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      ambassador_id: {{ $.Values.ambassador.ambassador_id }}
      tls: tls_context_{{ $.Values.peer.name }}_{{ $.Values.metadata.namespace }}_upstream
      grpc: True
      name: {{ $.Values.peer.name }}_{{ $.Values.metadata.namespace }}_mapping_rest
      #headers:
      #  :authority: {{ $.Values.peer.name }}.{{ $.Values.metadata.namespace }}.{{ $.Values.ambassador.external_url_suffix }}
      prefix: /
      rewrite: /
      service: {{ $.Values.peer.name }}.{{ $.Values.metadata.namespace }}:{{ $.Values.service.ports.grpc.clusteripport }}
  {{ end }}
  {{ if and $.Values.service.loadBalancerType (eq $.Values.service.loadBalancerType "Internal") }}
    cloud.google.com/load-balancer-type: "Internal"
  {{ end }}
  labels:
    run: {{ $.Values.peer.name }}
    app.kubernetes.io/name: {{ $.Values.peer.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "labels.custom" . | nindent 2 }}
spec:
  type: {{ $.Values.service.servicetype }}
  selector:
    app: {{ $.Values.peer.name }}
  ports:
  - name: grpc
    protocol: TCP
    targetPort: 7051
    port: {{ $.Values.service.ports.grpc.clusteripport }}
    {{- if $.Values.service.ports.grpc.nodeport }}
    nodePort: {{ $.Values.service.ports.grpc.nodeport }}
    {{- end }}
  - name: events
    protocol: TCP
    targetPort: 7053
    port: {{ $.Values.service.ports.events.clusteripport }}
    {{- if $.Values.service.ports.events.nodeport }}
    nodePort: {{ $.Values.service.ports.events.nodeport }}
    {{- end }}
  - protocol: TCP
    name: couchdb
    targetPort: 5984
    port: {{ $.Values.service.ports.couchdb.clusteripport }}
    {{- if $.Values.service.ports.couchdb.nodeport }}
    nodePort: {{ $.Values.service.ports.couchdb.nodeport }}
    {{ end }}
  {{ if (eq $.Values.service.servicetype "ClusterIP") }}
  clusterIP: None
  {{ end }}
  {{ if $.Values.service.loadBalancerIP }}
  loadBalancerIP: {{ $.Values.service.loadBalancerIP }}
  {{ end }}
