apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.peer.name }}
  namespace: {{ $.Values.metadata.namespace }}
  {{ if or $.Values.ambassador (and $.Values.service.loadBalancerType (eq $.Values.service.loadBalancerType "Internal")) }}
  annotations:
  {{ end }}
    service.beta.kubernetes.io/aws-load-balancer-type: {{ $.Values.service.loadBalancerType }}
    external-dns.alpha.kubernetes.io/hostname: "{{ $.Values.peer.name }}.{{ $.Values.metadata.namespace }}.{{ $.Values.ambassador.external_url_suffix }}."
  {{ if and $.Values.service.loadBalancerType (eq $.Values.service.loadBalancerType "Internal") }}
    cloud.google.com/load-balancer-type: "Internal"
  {{ end }}
  labels:
    run: {{ $.Values.peer.name }}
    app.kubernetes.io/name: {{ $.Values.peer.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "labels.custom" . | nindent 2 }}
spec:
  type: {{ $.Values.service.servicetype }}
  selector:
    app: {{ $.Values.peer.name }}
  ports:
  - name: grpc
    protocol: TCP
    targetPort: 7051
    port: {{ $.Values.service.ports.grpc.clusteripport }}
    {{- if $.Values.service.ports.grpc.nodeport }}
    nodePort: {{ $.Values.service.ports.grpc.nodeport }}
    {{- end }}
  - name: events
    protocol: TCP
    targetPort: 7053
    port: {{ $.Values.service.ports.events.clusteripport }}
    {{- if $.Values.service.ports.events.nodeport }}
    nodePort: {{ $.Values.service.ports.events.nodeport }}
    {{- end }}
  - protocol: TCP
    name: couchdb
    targetPort: 5984
    port: {{ $.Values.service.ports.couchdb.clusteripport }}
    {{- if $.Values.service.ports.couchdb.nodeport }}
    nodePort: {{ $.Values.service.ports.couchdb.nodeport }}
    {{ end }}
  {{ if (eq $.Values.service.servicetype "ClusterIP") }}
  clusterIP: None
  {{ end }}
  {{ if $.Values.service.loadBalancerIP }}
  loadBalancerIP: {{ $.Values.service.loadBalancerIP }}
  {{ end }}
