apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: mongodb-networkmap
  annotations:
    flux.weave.works/automated: "false"
  namespace: supplychain-ns
spec:
  replicaCount: 1
  replicas: 1
  releaseName: mongodb-networkmap
  chart:
    path: platforms/r3-corda/charts/mongodb
    git: ssh://git@innersource.accenture.com/sow11/blockchain-automation-framework.git
    ref: feature/bafdemo
  values:
    nodeName: mongodb-networkmap
    metadata:
      namespace: supplychain-ns
    image:
      containerName: mongo:3.6.6
      imagePullSecret: regcred
      initContainerName: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
    storage:
      memory: 512Mi
      name: awsstorageclass
      mountPath: /data/db
      volname: hostvol
    vault:
      address: http://a6b1eee14120111eabb36e61b3a46c3b-1570053847.eu-west-1.elb.amazonaws.com:9000
      role: vault-role
      authpath: cordanetworkmap
      secretprefix: networkmap/credentials/mongodb
      serviceaccountname: vault-auth
    service:
      tcp:
          port: 27017
          targetPort: 27017
      type: NodePort
      annotations: {}
    deployment:
      annotations: {}
    pvc:
      annotations: {}
    mongodb:
      username: networkmap