##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

helm_templates:
  dscp-api: dscp-api.tpl
  dscp-frontend: dscp-frontend.tpl
