apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: networkmapjv
  annotations:
    fluxcd.io/automated: "false"
  namespace: supplychainjv-ns
spec:
  releaseName: networkmapjv
  chart:
    path: platforms/r3-corda/charts/nms-tls
    git: ssh://git@github.com/jwavoetacn/blockchain-automation-framework.git
    ref: feature/1231-install-ambassador-fails-with-sourceips
  values:
    nodeName: networkmapjv
    metadata:
      namespace: supplychainjv-ns
    image:
      authusername: sa
      containerName: index.docker.io/hyperledgerlabs/networkmap-linuxkit:latest
      env:
      - name: NETWORKMAP_PORT
        value: 8080
      - name: NETWORKMAP_ROOT_CA_NAME
        value: CN=Network Map,OU=FRA,O=FRA,L=Berlin,C=DE
      - name: NETWORKMAP_TLS
        value: true
      - name: NETWORKMAP_DB
        value: /opt/networkmap/db
      - name: DB_USERNAME
        value: networkmapjv
      - name: NETWORKMAP_AUTH_USERNAME
        value: sa
      - name: DB_URL
        value: mongodb-networkmapjv
      - name: DB_PORT
        value: 27017
      - name: DATABASE
        value: admin
      - name: NETWORKMAP_CACHE_TIMEOUT
        value: 60S
      - name: NETWORKMAP_MONGOD_DATABASE
        value: networkmap
      imagePullSecret: regcred
      tlsCertificate: true
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      mountPath:
          basePath: /opt/networkmap
    storage:
      memory: 512Mi
      mountPath: "/opt/h2-data"
      name: awsstorageclass
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      role: vault-role
      authpath: cordanetworkmapjv
      serviceaccountname: vault-auth
      secretprefix: networkmapjv
      certsecretprefix: networkmapjv/certs
      dbcredsecretprefix: networkmapjv/credentials/mongodb
      secretnetworkmappass: networkmapjv/credentials/userpassword
      tlscertsecretprefix: networkmapjv/tlscerts
      dbcertsecretprefix: networkmapjv/certs
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
      dburl: mongodb-networkmapjv:27017
    service:
      port: 8080
      targetPort: 8080
      type: ClusterIP
      annotations: {}
    deployment:
      annotations: {}
    pvc:
      annotations: {}
    ambassador:
      external_url_suffix: rc.dev2.aws.blockchaincloudpoc-develop.com
      