- name: Check if Tiller is already installed in the Kubernetes clusters
  k8s_facts:
    kind: Pod
    namespace: kube-system
    kubeconfig: "{{ kubeconfig_path }}"
    label_selectors:
      - app = helm
    field_selectors:
      - status.phase=Running
  register: tiller_status

- name: Remove tiller
  shell: |
    KUBECONFIG={{ kubeconfig_path }} kubectl -n kube-system delete deployment tiller-deploy
  when: tiller_status.resources|length > 0

- name: Delete Tiller RBAC definintion
  k8s:
    state: absent
    kubeconfig: "{{ kubeconfig_path }}"
    kind: ClusterRoleBinding
    name: tiller-cluster-rule
  when: tiller_status.resources|length > 0

- name: Delete service account for Tiller
  k8s:
    state: absent
    kubeconfig: "{{ kubeconfig_path }}"
    kind: ServiceAccount
    namespace: kube-system
    name: tiller
  when: tiller_status.resources|length > 0
