apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychainsai-node-key-mgmt
  namespace: supplychainsai-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainsai-node-key-mgmt
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_key_mgmt
    sourceRef:
      kind: GitRepository
      name: flux-saikumar
      namespace: flux-saikumar
  values:
    metadata:
      name: supplychainsai-node-key-mgmt
      namespace: supplychainsai-bes
    image:
      besucontainer: hyperledger/besu:21.10.6
    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
      secretengine: secretsv2
      authpath: besusupplychainsai
      type: hashicorp
      role: vault-role
    organisation:
      namespace: supplychainsai-bes
      nodes:
        - name: validator1-saikumar
        - name: validator2-saikumar
