apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychainsaivalidator2-saikumarvalidator-node
  namespace: supplychainsai-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainsaivalidator2-saikumarvalidator-node
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_validator
    sourceRef:
      kind: GitRepository
      name: flux-saikumar
      namespace: flux-saikumar
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://2a9436092897307bfff1c399cf1b5e96c39ab9791f952ec29053bdcbb3466534de5e8ea29b662d83b53933b064866814cf14efd38d34650dda5292be9e4c25e1@validator1-saikumar.saikb.dev.aws.blockchaincloudpoc-develop.com:15010"
      - "enode://98ba7f59d80fecd55f13bbb570ded7a45243ee5e76c509fc8f30e7ffdfa6d50480e33a676898ef8c7c8e5027dfc25fdfa8453d394c6ed0b5406ff6b805568cbc@validator2-saikumar.saikb.dev.aws.blockchaincloudpoc-develop.com:15012"
      - "enode://c48b4cfd890b2e2878a6fcdd1f3402b97dda78fce324ab5dfa6d5a4aac511fe9d6d1666dfe540fe6267226606269883a976b77b9f677a83eff0262c0cc96c11d@carriersaikumar.saikb.dev.aws.blockchaincloudpoc-develop.com:15020"

    metadata:
      namespace: supplychainsai-bes
      labels:

    ambassador:
      external_url_suffix: saikb.dev.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false
    proxy:
      provider: ambassador
      external_url: supplychainsai.saikb.dev.aws.blockchaincloudpoc-develop.com
      p2p: 15012
      rpc: 15013

    images:
      node: hyperledger/besu:21.10.6
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullPolicy: IfNotPresent

    node:
      name: validator2-saikumar
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

      permissioning:
        enabled: False
      
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
      secretengine: secretsv2
      secretprefix: data/supplychainsai-bes/crypto/validator2-saikumar
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychainsai
      type: hashicorp

    genesis: 


    metrics:
      enabled: False
      port: 9545    
