#############################################################################################
# This role creates value files for service account
#############################################################################################

# Check service account exists already
- name: Check if service account for {{ component_name }} exists
  k8s_facts:
    kind: ServiceAccount
    name: "{{ component_name }}"
    namespace: "{{ component_namespace }}"
    kubeconfig: "{{ kubernetes.config_file }}"
  register: serviceaccount_state

# Create vault auth service account
- name: Create vault auth service account for {{ component_name }}
  include_role:
    name: create/k8_component
  vars:
    component_type: "service-account"
    component_type_name: "{{ component_name }}"
  when: storageclass_state.resources|length == 0
