apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vitalam-ipfs.fullname" . }}-config
  labels:
    {{- include "vitalam-ipfs.labels" . | nindent 4 }}
data:
  healthCheckPort: {{ .Values.config.healthCheckPort | quote }}
  logLevel: {{ .Values.config.logLevel }}
  nodeHost: {{ .Values.config.nodeHost }}
  ipfsCommand: {{ .Values.config.ipfsCommand }}
  ipfsLogLevel: {{ .Values.config.ipfsLogLevel }}
  ipfsArgs: {{ .Values.config.ipfsArgs | toJson | quote }}
  {{- if .Values.config.ipfsBootNodeAddress }}
  ipfsBootNodeAddress: {{ .Values.config.ipfsBootNodeAddress }}
  {{- end }}
  ipfsApiPort: {{ include "vitalam-ipfs.ipfsApiPort" . }}
  ipfsSwarmPort: {{ .Values.config.ipfsSwarmPort | quote }}
  dataVolumeSize: {{ .Values.storage.dataVolumeSize | quote }}
