---
galaxy_info:
  author: Accenture
  description: Role to setup the AWS command line interface.
  license: apache2
  min_ansible_version: 2.7
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - amazon
    - cloud
    - aws
    - s3
dependencies:
  - saucelabs-ansible.pip