ambassadortls: "{{playbook_dir}}/build/quorum/{{component_name}}/{{ node_name }}/tls"
rootca: "{{playbook_dir}}/build/quorum/quorumrootca"
cert_subject: '/C=UK/L=London/OU=DLT/O=DLT/CN=Quorum Root CA'