##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: A Helm chart for deploying VitalAM frontend for substrate
name: vitalam-frontend
version: 0.2.0
