apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: authority-baf-ac-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-baf-ac-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: git@github.com:jsarica/blockchain-automation-framework.git
    ref: local
  values:
    metadata:
      name: authority-baf-ac-auth-job
      namespace: authority-ns
    network:
      name: ephasus
      kubernetes_url: https://192.168.99.114:8443
    image:
      name: authority
      repository: alpine:3.9.4
    vault:
      address: http://0.0.0.0:8200
      keyPath: authority.baf-ac
      identity: baf-ac
      admin_auth_path: kubernetes-authority-admin-auth
      policy: authority-baf-ac-ro
      policy_content: path \"/authority/+/+/+/public*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-authority-baf-ac-auth
    account:
      admin_service: authority-admin-vault-auth
      admin_role: rw
      service: authority-baf-ac-vault-auth
      role: ro
