apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-manufacturer
  namespace: manufacturer-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-manufacturer
  chart:
    git: ssh://git@innersource.accenture.com/sow11/blockchain-automation-framework.git
    ref: feature/bafdemo
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: manufacturer-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.manufacturer-net.hf.demo.aws.blockchaincloudpoc.com:8443
      localmspid: manufacturerMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9000
      authpath: manufacturer-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/manufacturer-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/manufacturer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer.hf.demo.aws.blockchaincloudpoc.com:8443
    anchorstx: |-
      CosCChAKDggCIgphbGxjaGFubmVsEvYBCvMBCgphbGxjaGFubmVsEl8SXQoLQXBwbGljYXRpb24S
      TggBEkIKD21hbnVmYWN0dXJlck1TUBIvGgcKA01TUBIAIgsKB1dyaXRlcnMSACIKCgZBZG1pbnMS
      ACILCgdSZWFkZXJzEgAqBkFkbWlucxqDARKAAQoLQXBwbGljYXRpb24ScQgBEmUKD21hbnVmYWN0
      dXJlck1TUBJSCAEaFwoLQW5jaG9yUGVlcnMSCBoGQWRtaW5zGgcKA01TUBIAIgsKB1JlYWRlcnMS
      ACILCgdXcml0ZXJzEgAiCgoGQWRtaW5zEgAqBkFkbWlucyoGQWRtaW5z

