# Get all Helm Releases resources in the namespace
- name: Get all Helm Releases in the namespace
  k8s_info:
    api_version: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    namespace: "{{ item.name | lower }}-bes"
  register: helm_releases_raw
  loop: "{{ network['organizations'] }}"

# Using array to store helm release name and its namespace
- name: Set fact
  set_fact: 
    helm_result: []
    
# Extracting release name and its namespace
- name: Print all Helm releases in the namespace
  include_tasks: nested.yaml
  loop: "{{ helm_releases_raw.results | list }}"
  loop_control:
    loop_var: resources

# Patching all Helm Releases resources
- name: Patching
  k8s:
    api_version: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    namespace: "{{ item.ns }}"
    name: "{{ item.release_name }}"
    state: present
    definition:
      metadata:
        finalizers: []
  with_items: "{{ helm_result }}"
  register: patch_result

# Deleting all Helm Releases resources
- name: Delete all Helm Releases in the namespace
  k8s:
    api_version: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    namespace: "{{ item.ns }}"
    name: "{{ item.release_name }}"
    state: absent
  with_items: "{{ helm_result }}"
  register: delete_result
