apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: approve-storekd-allchannel-peer0supplychain1-1
  namespace: storekd-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: approve-storekd-allchannel-peer0supplychain1-1
  chart:
    git: https://github.com/deepakkumardbd/blockchain-automation-framework.git
    ref: dev
    path: platforms/hyperledger-fabric/charts/approve_chaincode
  values:
    metadata:
      namespace: storekd-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.storekd-net:7051
      localmspid: storekdMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://a0444dfa88c894a34871b0a1725c8647-1759960141.eu-west-1.elb.amazonaws.com:20002
      authpath: kdstorekd-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/storekd-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/storekd-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: ordererkd1.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.0
      name: supplychain
      version: 1
      sequence: 1
      commitarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
