apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: storekd-peer0
  namespace: storekd-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: storekd-peer0
  chart:
    git: https://github.com/deepakkumardbd/blockchain-automation-framework.git
    ref: dev
    path: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: storekd-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        
    peer:
      name: peer0
      gossippeeraddress: peer0.storekd-net:7051
      gossipexternalendpoint: peer0.storekd-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: storekdMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.0
      couchdb:
        username: storekd-user

    storage:
      peer:
        storageclassname: storekdsc
        storagesize: 512Mi
      couchdb:
        storageclassname: storekdsc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://a0444dfa88c894a34871b0a1725c8647-1759960141.eu-west-1.elb.amazonaws.com:20002
      authpath: kdstorekd-net-auth
      secretprefix: secret/crypto/peerOrganizations/storekd-net/peers/peer0.storekd-net
      secretambassador: secret/crypto/peerOrganizations/storekd-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secret/credentials/storekd-net/couchdb/storekd?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "haproxy"
      external_url_suffix: hf.dev2.aws.blockchaincloudpoc-develop.com
