apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: carrier-expressapi
  namespace: carrier-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  chart:
    path: examples/supplychain-app/charts/expressapp
    git: "ssh://git@innersource.accenture.com/sow11/blockchain-automation-framework.git"
    ref: "feature/bafdemo"
  releaseName: carrier-expressapi
  values:
    nodeName: carrier-expressapi
    metadata:
      namespace: carrier-net
    replicaCount: 1
    expressapp:
      serviceType: ClusterIP
      image: adopblockchaincloud0502.azurecr.io/supplychain_fabric/express_app:latest
      pullPolicy: Always
      pullSecrets: regcred
      nodePorts:
        port: 3000
        targetPort: 3000
        name: tcp
      env:
        apiUrl: http://carrier-restserver.carrier-net:20001/api/v1
    ambassador:
      name: carrier
      type: fabric
      external_url_suffix: fabric.demo.blockchaincloudpoc.com
      peer_name: peer0
