apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: instantiate-carrier-peer0-allchannel-supplychain1
  namespace: carrier-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: instantiate-carrier-peer0-allchannel-supplychain1
  chart:
    git: ssh://git@innersource.accenture.com/sow11/blockchain-automation-framework.git
    ref: feature/bafdemo
    path: platforms/hyperledger-fabric/charts/instantiate_chaincode
  values:
    metadata:
      namespace: carrier-net
    peer:
      name: peer0
      address: peer0.carrier-net.demo.fabric.blockchaincloudpoc.com:8443
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://a6b1eee14120111eabb36e61b3a46c3b-1570053847.eu-west-1.elb.amazonaws.com:9000
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer.demo.fabric.blockchaincloudpoc.com:8443
    chaincode:
      name: supplychain
      version: 1
      instantiationarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel