apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: join-allchannel-carrier-peer0
  namespace: carrier-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: join-allchannel-carrier-peer0
  chart:
    git: ssh://git@innersource.accenture.com/sow11/blockchain-automation-framework.git
    ref: feature/bafdemo
    path: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: carrier-net

    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://a6b1eee14120111eabb36e61b3a46c3b-1570053847.eu-west-1.elb.amazonaws.com:9000
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer.demo.fabric.blockchaincloudpoc.com:8443
    anchorstx: |-
      CsECChAKDggCIgphbGxjaGFubmVsEqwCCqkCCgphbGxjaGFubmVsEloSWAoLQXBwbGljYXRpb24S
      SQgBEj0KCmNhcnJpZXJNU1ASLxoHCgNNU1ASACILCgdXcml0ZXJzEgAiCgoGQWRtaW5zEgAiCwoH
      UmVhZGVycxIAKgZBZG1pbnMavgESuwEKC0FwcGxpY2F0aW9uEqsBCAESngEKCmNhcnJpZXJNU1AS
      jwEIARpUCgtBbmNob3JQZWVycxJFEjsKOQo0cGVlcjAuY2Fycmllci1uZXQuZGVtby5mYWJyaWMu
      YmxvY2tjaGFpbmNsb3VkcG9jLmNvbRD7QRoGQWRtaW5zGgcKA01TUBIAIgsKB1JlYWRlcnMSACIL
      CgdXcml0ZXJzEgAiCgoGQWRtaW5zEgAqBkFkbWlucyoGQWRtaW5z
 