apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: join-allchannel-carrier-peer0
  namespace: carrier-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: join-allchannel-carrier-peer0
  chart:
    git: ssh://git@innersource.accenture.com/sow11/blockchain-automation-framework.git
    ref: feature/bafdemo
    path: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: carrier-net

    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://a7138542f18e311ea802e062682cead8-2102258106.eu-west-1.elb.amazonaws.com:9000
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer.fabric.demo.blockchaincloudpoc.com:8443
    anchorstx: |-
      CsECChAKDggCIgphbGxjaGFubmVsEqwCCqkCCgphbGxjaGFubmVsEloSWAoLQXBwbGljYXRpb24S
      SQgBEj0KCmNhcnJpZXJNU1ASLxoHCgNNU1ASACILCgdSZWFkZXJzEgAiCwoHV3JpdGVycxIAIgoK
      BkFkbWlucxIAKgZBZG1pbnMavgESuwEKC0FwcGxpY2F0aW9uEqsBCAESngEKCmNhcnJpZXJNU1AS
      jwEIARoHCgNNU1ASABpUCgtBbmNob3JQZWVycxJFEjsKOQo0cGVlcjAuY2Fycmllci1uZXQuZmFi
      cmljLmRlbW8uYmxvY2tjaGFpbmNsb3VkcG9jLmNvbRD7QRoGQWRtaW5zIgsKB1JlYWRlcnMSACIL
      CgdXcml0ZXJzEgAiCgoGQWRtaW5zEgAqBkFkbWlucyoGQWRtaW5z
 