apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.organization.name }}-domain-transactions-genesis
  namespace: {{ $.Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Values.organization.name }}-domain-transactions-genesis
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  domain_transactions_genesis: |
  {{ $.Values.configmap.domainGenesis  | nindent 6 }}
