##############################################################################################
# This role check trustee and stewards crypto in Vault
##############################################################################################

##############################################################################################
# Check if Indy Key management pod for trustee is completed
- name: Check if Indy Key management pod for trustee is completed
  vars:
    identity_name: "{{ trusteeItem.name }}"
  k8s_facts:
    kind: Pod
    namespace: "{{ component_ns }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
    label_selectors:
      - name = "{{ component_name }}-{{ identity_name }}"
    field_selectors:
      - status.phase=Completed
  register: indy-key-mgmt-tool
  until: indy-key-mgmt-tool.resources|length > 0
  retries: 10
  delay: 40
  loop: "{{ services.trustees }}"
    loop_control:
      loop_var: trusteeItem

##############################################################################################
# Check if Indy Key management pod for stewards is completed
- name: Check if Indy Key management pod for stewards is completed
  vars:
    identity_name: "{{ stewardItem.name }}"
  k8s_facts:
    kind: Pod
    namespace: "{{ component_ns }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
    label_selectors:
      - name = "{{ component_name }}-{{ identity_name }}"
    field_selectors:
      - status.phase=Completed
  register: indy-key-mgmt-tool
  until: indy-key-mgmt-tool.resources|length > 0
  retries: 10
  delay: 40
  loop: "{{ services.stewards }}"
    loop_control:
      loop_var: stewardItem

##############################################################################################
# Check trustee in vault
- name: "Check trustee in vault"
  environment:
    VAULT_TOKEN: "{{ vault.root_token }}"
    VAULT_ADDR: "{{ vault.url }}"
    shell: |
      vault kv get -field=did {{ organization }}/trustee/{{ trusteeItem.name }}
    loop: "{{ services.trustees }}"
    loop_control:
      loop_var: trusteeItem

##############################################################################################
# Check stewards in vault
- name: "Check stewards in vault"
  environment:
    VAULT_TOKEN: "{{ vault.root_token }}"
    VAULT_ADDR: "{{ vault.url }}"
    shell: |
      vault kv get -field=did {{ organization }}/stewards/{{ stewardItem.name }}
    loop: "{{ services.stewards }}"
    loop_control:
      loop_var: stewardItem
