# This role calls for ambassador certificates creation for each component of CENM and notary
---
- name: Create Ambassador Certificates for CENM & Notary
  include_tasks: nested_main.yaml
  loop: "{{ org.services }}"
  loop_control:
    loop_var: peer

