---
  - name: install aws cli using pip
    pip:
      name: awscli
      umask: "0022"
    become: "{{ privilege_escalate | bool }}"
    tags:
      - aws_cli

  - name: configuring aws
    shell: |
      cd {{ aws_cli.bin_directory }}/
      ./aws configure set aws_access_key_id {{ aws_access_key }}
      ./aws configure set aws_secret_access_key {{ aws_secret_key }}
    changed_when: false
    tags:
      - notest
