apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: supplychainpkigenerator
  namespace: supplychain-ent
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainpkigenerator
  chart:
    git: ssh://git@innersource.accenture.com/sow11/blockchain-automation-framework.git
    ref: corda-ent
    path: platforms/corda-ent/charts/generate-pki
  values:
    nodeName: supplychain-pki
    replicas: 1
    metadata:
      namespace: supplychain-ent
    dockerImagePki:
      name: corda/enterprise-pkitool
      tag: 1.2-zulu-openjdk8u242
      pullPolicy: Always
    image:
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagePullSecret: regcred
    volume:
      baseDir: /opt/corda
    vault:
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9000
      role: vault-role
      authpath: cordaentsupplychain
      serviceaccountname: vault-auth
      certsecretprefix: secret/cenm
    healthcheck:
      readinesscheckinterval: 20
      readinessthreshold: 20
    serviceSsh:
      type: ClusterIP
      port: 2222
      targetPort: 2222
      nodePort:
    shell:
      user: signer
      password: signerP
    idmanPublicIP: idman.rce.demo.aws.blockchaincloudpoc.com
    idmanPort: 10001
    serviceLocations:
      identityManager:
        host: idman-internal
        port: 5052
      networkMap:
        host: networkmap-internal
        port: 5050
      revocation:
        port: 5053
    signers:
      CSR:
        schedule:
          interval: 1m 
      CRL:
        schedule:
          interval: 1d
      NetworkMap:
        schedule:
          interval: 1m
      NetworkParameters:
        schedule:
          interval: 1m
    cordaJarMx: 1
    healthCheckNodePort: 0
    jarPath: bin
    configPath: etc
    pki:
      certificates:
        tlscrlsigner:
          subject: "CN=Test TLS Signer Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
          crl:
            issuer: "CN=Corda TLS CRL Authority,OU=Corda UAT,O=R3 HoldCo LLC,L=New York,C=US"
        cordarootca:
          subject: "CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB"
        subordinateca:
          subject: "CN=Test Subordinate CA Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
        identitymanagerca:
          subject: "CN=Test Identity Manager Service Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
        networkmap:
          subject: "CN=Test Network Map Service Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
