apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: doormanjv
  annotations:
    fluxcd.io/automated: "false"
  namespace: supplychainjv-ns
spec:
  releaseName: doormanjv
  chart:
    path: platforms/r3-corda/charts/doorman-tls
    git: ssh://git@github.com/jwavoetacn/blockchain-automation-framework.git
    ref: feature/1231-install-ambassador-fails-with-sourceips
  values:
    nodeName: doormanjv
    metadata:
      namespace: supplychainjv-ns
    image:
      authusername: sa
      containerName: index.docker.io/hyperledgerlabs/doorman-linuxkit:latest
      env:
      - name: DOORMAN_PORT
        value: 8080
      - name: DOORMAN_ROOT_CA_NAME
        value: CN=Corda Doorman CA,OU=DLT,O=DLT,L=Berlin,C=DE
      - name: DOORMAN_TLS
        value: true
      - name: DOORMAN_DB
        value: /opt/doorman/db
      - name: DOORMAN_AUTH_USERNAME
        value: sa
      - name: DB_URL
        value: mongodb-doormanjv
      - name: DB_PORT
        value: 27017
      - name: DATABASE
        value: admin
      - name: DB_USERNAME
        value: doormanjv
      imagePullSecret: regcred
      tlsCertificate: true
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      mountPath:
        basePath: /opt/doorman
    storage:
      memory: 512Mi
      name: awsstorageclass
    mountPath:
      basePath: /opt/doorman
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      role: vault-role
      authpath: cordadoormanjv
      serviceaccountname: vault-auth
      certsecretprefix: doormanjv/certs
      dbcredsecretprefix: doormanjv/credentials/mongodb
      secretdoormanpass: doormanjv/credentials/userpassword
      tlscertsecretprefix: doormanjv/tlscerts
      dbcertsecretprefix: doormanjv/certs
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
      dburl: mongodb-doormanjv:27017
    service:
      port: 8080
      targetPort: 8080
      type: ClusterIP
      annotations: {}
    deployment:
      annotations: {}
    pvc:
      annotations: {}
    ambassador:
      external_url_suffix: rc.dev2.aws.blockchaincloudpoc-develop.com
      
    
        