apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychainvalidator3ibft
  namespace: supplychain-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainvalidator3ibft
  chart:
    git: https://github.com/Roshan13046/blockchain-automation-framework.git
    ref: feature/510
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://9d9013087f08f3b750eb12cea1b471d8cf374f2e23ebe9c03ee331b36bcc952ba78b1422ef38f36b272dce5beb227f0c73f1a5906c5e2e4a298807a82da0ae56@validator1.supplychain-bes.svc.cluster.local:30303"
      
      - "enode://dd4f84efce45d3de6c6fc9551fa4713e4784896735d6f0593ebacf866413a7c434f00e957d26a06ca546230c40a7e64e1767db1a16ffb0eb485449097c04c3bc@validator2.supplychain-bes.svc.cluster.local:30303"
      
      - "enode://79f37da5935bc2343802cd56d4d9b4d7b3c7388769ea9f10d18e6f992b968b0e56aa5b3b53f595a0f15f903950c2038236978bc3f105b865eed396d5bd539925@validator3.supplychain-bes.svc.cluster.local:30303"
      
      - "enode://c1e561f58cdad7ca31d892e698d38470849dd50151d6bc019d04e8ff511a0d7111a6bb5be2504882f14195e0c799807b68b4b61e114aa8621f64ea387b8678d3@validator4.supplychain-bes.svc.cluster.local:30303"
      
      - "enode://12e99fcd7e689836d13b988a7590bd851a8bb968295052b894cc78d440db11f691d00d1fb1df5602d1d0cb49204e6622ade36af291d03d007cc97e61993b7ed8@carrier.carrier-bes.svc.cluster.local:30303"
      
      - "enode://21d28214981d1759fc398a478888e702841e1cdd7db31b357ad6290fd9e63c24a626b0a9d3f4c7f3fde14cb1ab2bbe7f91101841adc686e028834daeccf529e1@manufacturer.manufacturer-bes.svc.cluster.local:30303"
      
      - "enode://1590eb5cfe6bee9fafe5a2bf34f77a3d3e759bbc2dc9bba35aced5a38f22608cf093d34e7b9f5405a8a55add2629551919802796b4dfb87b5a637160cfeb3caa@store.store-bes.svc.cluster.local:30303"
      
      - "enode://2e86c460d76584d8c8873e70aec82ff8826e5845bd7f58735b9dfda6862e9402a017e6da2967886d08f608446e8b742795633ff6199722e1f2755764bc89c4a1@warehouse.warehouse-bes.svc.cluster.local:30303"
      

    metadata:
      namespace: supplychain-bes
      labels:

    ambassador:
      external_url_suffix: supplychain-bes.svc.cluster.local

    liveliness_check:
      enabled: false
      
    proxy:
      provider: none
      external_url: supplychain.supplychain-bes
      p2p: 30303
      rpc: 8545

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator3
      tls: True
      consensus: clique
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: gcpstorageclass
      storagesize: 1Gi

    vault:
      address: http://10.128.0.26:8200
      secretprefix: secret/supplychain-bes/crypto/validator3
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychain

    genesis: 
