apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: idsidsmember-node
  namespace: ids-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: idsidsmember-node
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_besu
    sourceRef:
      kind: GitRepository
      name: flux-prod
      namespace: flux-prod
  values:
    metadata:
      namespace: ids-bes
      labels:
    replicaCount: 1
    staticnodes:
      - "enode://cec65122445670b44927311333bf2e502bb304d7eec1a3fc0c928dbb098a7fa2bd62bc496891273dc504a03fbe5ef4841a5be19ac4af123b8798d96c444274bb@validator1.app.bharatblockchain.io:15010"
      - "enode://2168faa11b3b6e2eeac7b4b3e92a37d589f9a87e48c2dca261ddb7143e3679cf8573e637339875c522edaaa80f02ca9cbe7adcceb37d3361e826a50835f59b35@validator2.app.bharatblockchain.io:15012"
      - "enode://71388bef683c2a670ab7202e5648d38b08e42d9aaf760ce1fd1bd7ecac048b93c18eb0248c39e12182c541bdac875f0e99e2c85fcfa9917e3eee391f4c24de1d@validator3.app.bharatblockchain.io:15014"
      - "enode://33c95c215e55bda4c3d00acd53ffaac05f0120715f0c5fc2faed261d88783f4c936ef00771b6fdae77d8741956c1d963ed8f3f3d3df33d3375deb420ece6a8ca@validator4.app.bharatblockchain.io:15016"
      - "enode://f4102bc55230f69a623c1d2e2d027266b9c7824cf75bee789cbbef9b1c9fff4175c9173050ebf9f2b82550a143341d8f5a006f36b6a95e3aab0ca0b79071fe99@ids.app.bharatblockchain.io:15020"

    liveliness_check:
      enabled: false
    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5
    proxy:
      provider: ambassador
      external_url: ids.app.bharatblockchain.io
      p2p: 15020
      rpc: 15021

    images:
      node: hyperledger/besu:21.10.6
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      pullPolicy: IfNotPresent

    node:
      name: ids
      consensus: ibft
      subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    tm:
      type: tessera
      tls: True
      url: "https://ids-tessera.ids-bes:8888"

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://afaa81f5113c849ca8e7cad72f262df9-2626065.ap-south-1.elb.amazonaws.com:8200
      secretprefix: secretsv2/data/ids-bes/crypto/ids
      serviceaccountname: vault-auth
      keyname: data
      tmdir: tm
      tlsdir: tls
      role: vault-role
      authpath: besuids

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDBjNmZlZjgzZmZhNmExNDgxZTAxZDM3ODc3NDJhM2QxYjk5YjE3MDU5NDVlYTYyNmZhNTljZDg2ZGIzODJiZjY3MjIxYTVmYWU5NDcwYjI4NmU5NGE0Yzk2NTYzZDM3Njc0M2JjMWU1Njk1MjY2ZDM1MTkyZTRmNGFmYjY5NDJlNmFiNTgyNDAzMmE5MWJiZmQ3N2Y1Y2I1OGE1MzExYWM3ZmY5ZjE4MDg0MDAwMDAwMDBjMCIKfQ==
