apiVersion:  helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: idstessera
  namespace: ids-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: idstessera
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_tessera
    sourceRef:
      kind: GitRepository
      name: flux-prod
      namespace: flux-prod
  values:
    replicaCount: 1
    metadata:
      namespace: ids-bes
      labels:
    images:
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:hashicorp-21.7.3
      busybox: busybox
      mysql: mysql/mysql-server:5.7
      imagePullSecret: regcred
      pullPolicy: IfNotPresent
    tessera:
      name: ids-tessera
      dbname: demodb
      dburl: "jdbc:mysql://ids-tessera:3306/demodb"
      dbusername: demouser
      tls: "STRICT"
      url: "https://ids.app.bharatblockchain.io:443"
      clienturl: "https://ids-tessera:8888"
      othernodes:
        - url: https://ids.app.bharatblockchain.io
        - url: https://aicte.app.bharatblockchain.io
        - url: https://validator1.app.bharatblockchain.io
        - url: https://validator2.app.bharatblockchain.io
        - url: https://validator3.app.bharatblockchain.io
        - url: https://validator4.app.bharatblockchain.io
        - url: https://ids-tessera.ids-bes
        - url: https://aicte-tessera.aicte-bes
      trust: "TOFU"

      servicetype: ClusterIP
      ports:
        tm: 443
        db: 3306
        client: 8888
      mountPath: /etc/tessera/data
      ambassadorSecret: ids-ambassador-certs
    vault:
      address: http://afaa81f5113c849ca8e7cad72f262df9-2626065.ap-south-1.elb.amazonaws.com:8200
      secretengine: secretsv2
      tmsecretpath: ids-bes/crypto/ids/tm
      secretprefix: secretsv2/data/ids-bes/crypto/ids
      serviceaccountname: vault-auth
      keyname: credentials
      tm_keyname: tm
      tlsdir: tls
      role: vault-role
      authpath: besuids
    proxy:
      provider: "ambassador"
      external_url: ids.app.bharatblockchain.io
      portTM: 443
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
