---
tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp',true) }}"
constellation:
  repo: https://github.com/jpmorganchase/constellation/releases/download/v{{version}}/constellation-{{version}}-ubuntu1604.tar.xz
