#########################
# Playbook to cleanup platform from the cluster
# Playbook arguments: complete network.yaml
#########################
- hosts: ansible_provisioners
  gather_facts: no
  tasks:
  # ----------------------------------------------------------------------

  # Cleanup all organizations' Vault indy crypto
  - name: Cleanup Vault indy crypto
    include_role:
      name: clean/vault
    vars:
      organization: "{{ organizationItem.name | lower }}"
      acount: "{{ organization }}-admin-vault-auth"
      vault: "{{ organizationItem.vault }}"
      role: "rw"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organizationItem
    when: network['type'] == 'indy'

  # Cleanup Flux release folder in Git for all organizations

  # Delete all organizations' namespaces with all K8S resources (including PVCs and PVs)

  # Delete the Flux Helm release from all organizations's K8S clusters (including the Git secret)

  # Delete Tiller from all organizations' K8S clusters

  # Rollback all changes done on the Ansible controller (Vault client, Helm client, Kubects, AWS cli ...)