userpassword_networkmap: admin
mongodbPassword_networkmap: newdbnm
rootca: "{{playbook_dir}}/build/corda/cordarootca"
nmsca: "{{playbook_dir}}/build/corda/cordanetworkmap"
mongorootca: "{{playbook_dir}}/build/corda/mongorootca"
mongodbca: "{{playbook_dir}}/build/corda/mongodbca"
mongoroot_cert_subj: /C=US/ST=California/L=San Francisco/O=My Company Ltd/OU=DBA/CN=mongoDB
mongodb_cert_subj: "/C=GB/ST=London/L=London/O=Networkmap/OU=OnlineServices/CN=mongodb-{{component_name}}"