# This role calls for ambassador certifacate creation for each node.
---
- name: Create Ambassador certificates
  include_role: 
    name: "create/certificates/ambassador"
  vars:
    node_name: "{{ node.name | lower }}"
  loop: "{{ services.peers }}"
  loop_control:
    loop_var: node
