metadata:
  namespace:
  #baf
  name:
  #indy-key-mgmt

network:
  name:

image:
  name:
  #indy-key-mgmt
  repository:
  #indy-key-mgmt:latest
  pullPolicy:
  #Always
  restartPolicy:
  #OnFailure
  pullSecret:
  #baf

vault:
  address:
  #http://vault:8200
  keyPath:
  #provider.stewards
  identity:
  #my-identity

account:
  service:
  # vault-auth-provider-agent-app
  role:
  # ro