apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inteli-demo.fullname" . }}-config
  labels:
    {{- include "inteli-demo.labels" . | nindent 4 }}
data:
  config.js: |-
{{ tpl (.Files.Get "files/config.js.tpl") . | indent 4 }}
