##############################################################################################
# This role creates the value file for signer
##############################################################################################

# create deployment file for CENM signer service
- name: "create signer"
  include_role:
    name: create/k8_component
  vars:
    component_name: "{{ services.signer.name }}"
    component_type: "signer"
    helm_lint: "true"
    charts_dir: "{{ gitops.chart_source }}"
    component_auth: "corda{{ services.doorman.name | lower }}"
    org: "{{ item }}"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}"

# Push the signer deployment files to repository
- name: "Push the created deployment files to repository"
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    GIT_REPO: "{{ gitops.git_push_url }}"
    GIT_USERNAME: "{{ gitops.username }}"
    GIT_EMAIL: "{{ gitops.email }}"
    GIT_PASSWORD: "{{ gitops.password }}"
    GIT_BRANCH: "{{ gitops.branch }}"
    GIT_RESET_PATH: "platforms/r3-corda/configuration"
    msg: "[ci skip] Pushing deployment files for signer service"
  tags:
    - notest
