#############################################################################################
# This role creates value files for service account for vault
#############################################################################################

# Create service account per identity of trustees
- name: Create service account for trustees [{{ organization }}]
  include_role:
    name: create/serviceaccount/by_identities
  vars:
    component_namespace: "{{ component_ns }}"
    component_name: "{{ trusteeItem.name }}-vault-auth"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}/{{ organization }}"
  loop: "{{ services.trustees }}"
  loop_control:
    loop_var: trusteeItem
  when: services.trustees is defined

# Create service account per identity of stewards
- name: Create service account for stewards [{{ organization }}]
  include_role:
    name: create/serviceaccount/by_identities
  vars:
    component_namespace: "{{ component_ns }}"
    component_name: "{{ stewardItem.name }}-vault-auth"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}/{{ organization }}"
  loop: "{{ services.stewards }}"
  loop_control:
    loop_var: stewardItem
  when: services.stewards is defined

# Create service account per identity of endorsers
- name: Create service account for endorsers [{{ organization }}]
  include_role:
    name: create/serviceaccount/by_identities
  vars:
    component_namespace: "{{ component_ns }}"
    component_name: "{{ endorserItem.name }}-vault-auth"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}/{{ organization }}"
  loop: "{{ services.endorsers }}"
  loop_control:
    loop_var: endorserItem
  when: services.endorsers is defined

# Create service account per organizations
- name: Create service account for organization [{{ organization }}]
  include_role:
    name: create/serviceaccount/by_identities
  vars:
    component_namespace: "{{ component_ns }}"
    component_name: "{{ organization }}-admin-vault-auth"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}/{{ organization }}"

# Create service account for read only public crypto per organizations
- name: Create service account for read only public crypto [{{ organization }}]
  include_role:
    name: create/serviceaccount/by_identities
  vars:
    component_namespace: "{{ component_ns }}"
    component_name: "{{ organization }}-baf-ac-vault-auth"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}/{{ organization }}"

# Push the deployment files to repository
- name: "Push the created deployment files to repository"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    GIT_REPO: "{{ gitops.git_push_url }}"
    GIT_USERNAME: "{{ gitops.username }}"
    GIT_PASSWORD: "{{ gitops.password }}"
    GIT_BRANCH: "{{ gitops.branch }}"
    GIT_RESET_PATH: "platforms/hyperledger-indy/configuration"
    msg: "Pushing deployment file for service account"

- name: "Wait for creation for trustees accounts"
  include_role:
    name: check/k8_component
  vars:
    component_type: "ServiceAccount"
    component_name: "{{ trusteeItem.name }}-vault-auth"
    kubeconfig: "{{ kubernetes.config_file }}"
  loop: "{{ services.trustees }}"
  loop_control:
    loop_var: trusteeItem
  when: services.trustees is defined

- name: "Wait for creation for stewards accounts"
  include_role:
    name: check/k8_component
  vars:
    component_type: "ServiceAccount"
    component_name: "{{ stewardItem.name }}-vault-auth"
    kubeconfig: "{{ kubernetes.config_file }}"
  loop: "{{ services.stewards }}"
  loop_control:
    loop_var: stewardItem
  when: services.stewards is defined

- name: "Wait for creation for endorsers accounts"
  include_role:
    name: check/k8_component
  vars:
    component_type: "ServiceAccount"
    component_name: "{{ endorserItem.name }}-vault-auth"
    kubeconfig: "{{ kubernetes.config_file }}"
  loop: "{{ services.endorsers }}"
  loop_control:
    loop_var: endorserItem
  when: services.endorsers is defined

- name: "Wait for creation for organization service account"
  include_role:
    name: check/k8_component
  vars:
    component_type: "ServiceAccount"
    component_name: "{{ organization }}-admin-vault-auth"
    kubeconfig: "{{ kubernetes.config_file }}"

- name: "Wait for creation for read only public crypto service account"
  include_role:
    name: check/k8_component
  vars:
    component_type: "ServiceAccount"
    component_name: "{{ organization }}-baf-ac-vault-auth"
    kubeconfig: "{{ kubernetes.config_file }}"
