apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: authority-baf-ac-va-role-binding
  namespace: authority-ns
  labels:
    organization: authority
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: authority-baf-ac-va
  namespace: authority-ns
