apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: warehouse-springboot
  namespace: warehouse-ns
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: warehouse-springboot
  chart:
    path: examples/supplychain-app/charts/springbootwebserver
    git: "ssh://git@innersource.accenture.com/sow11/blockchain-automation-framework.git"
    ref: "corda"
  values:
    nodeName: warehouse-springboot
    replicas: 1
    metadata:
      namespace: warehouse-ns
    image:
      containerName: index.docker.io/hyperledgerlabs/supplychain_corda:springboot_latest
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
    smartContract:
      JAVA_OPTIONS : -Xmx512m
    volume:
      mountPath: /opt/corda
    nodeConf:
      node: warehouse
      nodeRpcPort: 10003
      nodeRpcAdminPort: 10005
      controllerName: Controller
      trustStorePath: /opt/corda/certificates/sslkeystore.jks
      trustStoreProvider: jks
      legalName: O=Warehouse,OU=Warehouse,L=42.36/-71.06/Boston,C=US
      devMode: false
      useHTTPS: true
      useSSL: false
      tlsAlias: cordaclienttls
      ssl:
        certificatesDirectory: na-ssl-false
        sslKeystoreFileName: na-ssl-false
        ssltruststore: na-ssl-false
    credentials:
      rpcUser: warehouseoperations
    resources:
      limits: "512Mi"
      requests: "512Mi"
    storage:
      provisioner: kubernetes.io/aws-ebs
      memory: 512Mi
      name: awsstorageclass
      parameters:
        type: gp2
        encrypted: "true"
      annotations: {}
    web:
      targetPort: 20001
      port: 20001
    service:
      type: NodePort
      annotations: {}
    vault:
      address: "http://vault.internal.demo.aws.blockchaincloudpoc.com:9000"
      role: vault-role
      authpath: cordawarehouse
      serviceaccountname: vault-auth
      rpcusersecretprefix: warehouse/credentials/rpcusers
      keystoresecretprefix: warehouse/credentials/keystore
      certsecretprefix: warehouse/certs
    node:
      readinesscheckinterval: 10
      readinessthreshold: 15
    deployment:
      annotations: {}
    pvc:
      annotations: {}
