apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: carrier-net-ca
  namespace: carrier-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carrier-net-ca
  chart:
    git: ssh://git@innersource.accenture.com/sow11/blockchain-automation-framework.git
    ref: feature/bafdemo
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: carrier-net
    server:
      name: ca
      tlsstatus: true
      admin: carrier-admin
    storage:
      storageclassname: carriersc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://a2f30bbf3fa6b11e9b7a50a059b1d738-111223046.eu-west-2.elb.amazonaws.com:9000
      authpath: carrier-net-auth
      secretcert: secret/crypto/peerOrganizations/carrier-net/ca?ca.carrier-net-cert.pem
      secretkey: secret/crypto/peerOrganizations/carrier-net/ca?carrier-net-CA.key
      secretadminpass: secret/credentials/carrier-net/ca/carrier?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    ambassador:
    #Provide annotations for ambassador service configuration
    #Only use HTTPS as HTTP and HTTPS don't work together ( https://github.com/datawire/ambassador/issues/1000 )
      annotations: |- 
        ---
        apiVersion: ambassador/v1
        kind:  Mapping
        name:  ca_carrier-net_mapping
        prefix: /
        host: ca.carrier-net:7054
        service: ca.carrier-net:7054
        tls: ca_carrier-net_tls
        ---
        apiVersion: ambassador/v1
        kind: TLSContext
        name: ca_carrier-net_tls
        hosts:
        - ca.carrier-net
        secret: ca-carrier-net-ambassador-certs
    