service:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Module
      name:  ambassador
      config:
        enable_grpc_http11_bridge: true
        enable_grpc_web: true
