---
#######################################
# Master Playbook for the setting up or reseting the Blockchain Automation Framework DLT network
#######################################
  - hosts: all
    gather_facts: no
  - import_playbook: environment-setup.yaml   # First setup environment for each organization
    when: reset == 'false' or reset is undefined
  - import_playbook: kubernetes-env-setup.yaml # Then deploy Flux for each organization
    when: reset == 'false' or reset is undefined
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-fabric/configuration/deploy-network.yaml"
    when: network.type == 'fabric' and (reset == 'false' or reset is undefined) 
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-fabric/configuration/chaincode-install-instantiate.yaml"
    when: network.type == 'fabric' and (reset == 'false' or reset is undefined)
  - import_playbook: "{{ playbook_dir }}/../../r3-corda/configuration/deploy-network.yaml"
    when: network.type == 'corda' and (reset == 'false' or reset is undefined) 
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-indy/configuration/deploy-network.yaml"
    when: network.type == 'indy' and (reset == 'false' or reset is undefined)

# Reseting the network 

  - import_playbook: "{{ playbook_dir }}/../../r3-corda/configuration/reset-network.yaml"
    when: network.type == 'corda' and reset == 'true'
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-fabric/configuration/reset-network.yaml"
    when: network.type == 'fabric' and reset == 'true'
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-indy/configuration/cleanup.yaml"
    when: network.type == 'indy' and reset == 'true'
