#############################################################################################
# This role saves the crypto from Vault into ansible_provisioner
#############################################################################################

# Ensure admincerts directory is present in build
- name: Ensure directory exists
  file:
    path: "{{ cert_path }}"
    recurse: yes
    state: directory

# Save the cert file
- name: Save cert
  local_action: copy content="{{ vault_output['data'].tlscacerts | b64decode }}" dest="{{ cert_path }}/{{ type }}.crt"
  when: type == 'ambassador'
# Save the key file
- name: Save key
  local_action: copy content="{{ vault_output['data'].tlskey | b64decode }}" dest="{{ cert_path }}/{{ type }}.key"
  when: type == 'ambassador'

- name: Save root keychain
  local_action: copy content="{{ vault_output['data'].rootcakey | b64decode }}" dest="{{ cert_path }}/keys.jks"
  when: type == 'rootca'

- name: Save root cert
  local_action: copy content="{{ vault_output['data'].cacerts | b64decode }}" dest="{{ cert_path }}/cordarootca.pem"
  when: type == 'rootca'

- name: Save root key
  local_action: copy content="{{ vault_output['data'].keystore | b64decode }}" dest="{{ cert_path }}/cordarootca.key"
  when: type == 'rootca'