apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-cakd-allchannel
  namespace: cakd-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-cakd-allchannel
  chart:
    git: https://github.com/deepakkumardbd/blockchain-automation-framework.git
    ref: dev
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: cakd-net
      network:
        version 2.2.0
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.cakd-net:7051
      localmspid: cakdMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://a0444dfa88c894a34871b0a1725c8647-1759960141.eu-west-1.elb.amazonaws.com:20002
      authpath: kdcakd-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/cakd-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/cakd-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: ordererkd1.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    channeltx: |-
      CuMDChgKFggCGgYIxOGZhAYiCmFsbGNoYW5uZWwSxgMKwwMKCmFsbGNoYW5uZWwSSxI5CgtBcHBs
      aWNhdGlvbhIqEg4KCnN0b3Jla2RNU1ASABILCgdjYWtkTVNQEgASCwoHbWFrZE1TUBIAGg4KCkNv
      bnNvcnRpdW0SABrnAhK7AgoLQXBwbGljYXRpb24SqwIIARIOCgpzdG9yZWtkTVNQEgASCwoHY2Fr
      ZE1TUBIAEgsKB21ha2RNU1ASABokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5z
      IjUKFExpZmVjeWNsZUVuZG9yc2VtZW50Eh0SEwgDEg8KC0VuZG9yc2VtZW50EAIaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIsCgtFbmRv
      cnNlbWVudBIdEhMIAxIPCgtFbmRvcnNlbWVudBACGgZBZG1pbnMqBkFkbWlucxonCgpDb25zb3J0
      aXVtEhkSFwoVU3VwcGx5Q2hhaW5Db25zb3J0aXVt